//
// Cart.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Cart: JSONEncodable {
    public var id: Int32?
    public var createDate: NSDate?
    public var modifyDate: NSDate?
    public var cartId: String?
    public var description: String?
    public var currentFulfillmentProcessId: Int32?
    public var currentWorkBatchId: Int32?
    public var positionType: String?
    public var customFields: [String:AnyObject]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["createDate"] = self.createDate?.encodeToJSON()
        nillableDictionary["modifyDate"] = self.modifyDate?.encodeToJSON()
        nillableDictionary["cartId"] = self.cartId
        nillableDictionary["description"] = self.description
        nillableDictionary["currentFulfillmentProcessId"] = self.currentFulfillmentProcessId?.encodeToJSON()
        nillableDictionary["currentWorkBatchId"] = self.currentWorkBatchId?.encodeToJSON()
        nillableDictionary["positionType"] = self.positionType
        nillableDictionary["customFields"] = self.customFields?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
