//
// ExternalShippingSystem.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ExternalShippingSystem: JSONEncodable {
    public var id: Int32?
    public var name: String?
    public var systemType: String?
    public var scriptId: Int32?
    public var explodeAllKitContents: Bool?
    public var apiKey: String?
    public var apiSecret: String?
    public var createDate: NSDate?
    public var modifyDate: NSDate?
    public var customFields: [String:AnyObject]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["name"] = self.name
        nillableDictionary["systemType"] = self.systemType
        nillableDictionary["scriptId"] = self.scriptId?.encodeToJSON()
        nillableDictionary["explodeAllKitContents"] = self.explodeAllKitContents
        nillableDictionary["apiKey"] = self.apiKey
        nillableDictionary["apiSecret"] = self.apiSecret
        nillableDictionary["createDate"] = self.createDate?.encodeToJSON()
        nillableDictionary["modifyDate"] = self.modifyDate?.encodeToJSON()
        nillableDictionary["customFields"] = self.customFields?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
