//
// FulfillmentProcessLog.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class FulfillmentProcessLog: JSONEncodable {
    public var id: Int32?
    public var createDate: NSDate?
    public var modifyDate: NSDate?
    public var processNoId: Int32?
    public var warehouseId: Int32?
    public var orderId: Double?
    public var lobId: Int32?
    public var skuId: Int32?
    public var locationId: Int32?
    public var itemReceiptId: Int32?
    public var allocationIssueType: String?
    public var message: String?
    public var customFields: [String:AnyObject]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["createDate"] = self.createDate?.encodeToJSON()
        nillableDictionary["modifyDate"] = self.modifyDate?.encodeToJSON()
        nillableDictionary["processNoId"] = self.processNoId?.encodeToJSON()
        nillableDictionary["warehouseId"] = self.warehouseId?.encodeToJSON()
        nillableDictionary["orderId"] = self.orderId
        nillableDictionary["lobId"] = self.lobId?.encodeToJSON()
        nillableDictionary["skuId"] = self.skuId?.encodeToJSON()
        nillableDictionary["locationId"] = self.locationId?.encodeToJSON()
        nillableDictionary["itemReceiptId"] = self.itemReceiptId?.encodeToJSON()
        nillableDictionary["allocationIssueType"] = self.allocationIssueType
        nillableDictionary["message"] = self.message
        nillableDictionary["customFields"] = self.customFields?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
