//
// LoadContent.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class LoadContent: JSONEncodable {
    public var id: Int32?
    public var createDate: NSDate?
    public var modifyDate: NSDate?
    public var loadId: Int32?
    public var masterCartonId: Int32?
    public var lobId: Int32?
    public var cartonId: Int32?
    public var itemId: Int32?
    public var itemReceiptId: Int32?
    public var quantity: Int32?
    public var customFields: [String:AnyObject]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["createDate"] = self.createDate?.encodeToJSON()
        nillableDictionary["modifyDate"] = self.modifyDate?.encodeToJSON()
        nillableDictionary["loadId"] = self.loadId?.encodeToJSON()
        nillableDictionary["masterCartonId"] = self.masterCartonId?.encodeToJSON()
        nillableDictionary["lobId"] = self.lobId?.encodeToJSON()
        nillableDictionary["cartonId"] = self.cartonId?.encodeToJSON()
        nillableDictionary["itemId"] = self.itemId?.encodeToJSON()
        nillableDictionary["itemReceiptId"] = self.itemReceiptId?.encodeToJSON()
        nillableDictionary["quantity"] = self.quantity?.encodeToJSON()
        nillableDictionary["customFields"] = self.customFields?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
