//
// ReceivingProcess.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ReceivingProcess: JSONEncodable {

    public var id: Int?
    public var warehouseId: Int?
    public var status: String?
    public var workBatchId: Int?
    public var receivingWorksheetId: Int?
    public var createDate: NSDate?
    public var modifyDate: NSDate?
    

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id
        nillableDictionary["warehouseId"] = self.warehouseId
        nillableDictionary["status"] = self.status
        nillableDictionary["workBatchId"] = self.workBatchId
        nillableDictionary["receivingWorksheetId"] = self.receivingWorksheetId
        nillableDictionary["createDate"] = self.createDate?.encodeToJSON()
        nillableDictionary["modifyDate"] = self.modifyDate?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
