//
// ReturnOrder.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ReturnOrder: JSONEncodable {
    public var id: Int32?
    public var createDate: NSDate?
    public var modifyDate: NSDate?
    public var lobId: Int32?
    public var warehouseId: Int32?
    public var originalOrderNo: Double?
    public var reshipOrderNo: Double?
    public var returnAsnId: Int32?
    public var customerNo: String?
    public var shipToAttention: String?
    public var shipToCompany: String?
    public var shipToStreet: String?
    public var shipToStreet2: String?
    public var shipToStreet3: String?
    public var shipToCity: String?
    public var shipToState: String?
    public var shipToZip: String?
    public var shipToCountry: String?
    public var shipToPhone: String?
    public var shipToEmail: String?
    public var returnOrderStatus: String?
    public var returnReason: String?
    public var returnCategory: String?
    public var returnInstructions: String?
    public var returnOrderLineItemList: [ReturnOrderLine]?
    public var customFields: [String:AnyObject]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["createDate"] = self.createDate?.encodeToJSON()
        nillableDictionary["modifyDate"] = self.modifyDate?.encodeToJSON()
        nillableDictionary["lobId"] = self.lobId?.encodeToJSON()
        nillableDictionary["warehouseId"] = self.warehouseId?.encodeToJSON()
        nillableDictionary["originalOrderNo"] = self.originalOrderNo
        nillableDictionary["reshipOrderNo"] = self.reshipOrderNo
        nillableDictionary["returnAsnId"] = self.returnAsnId?.encodeToJSON()
        nillableDictionary["customerNo"] = self.customerNo
        nillableDictionary["shipToAttention"] = self.shipToAttention
        nillableDictionary["shipToCompany"] = self.shipToCompany
        nillableDictionary["shipToStreet"] = self.shipToStreet
        nillableDictionary["shipToStreet2"] = self.shipToStreet2
        nillableDictionary["shipToStreet3"] = self.shipToStreet3
        nillableDictionary["shipToCity"] = self.shipToCity
        nillableDictionary["shipToState"] = self.shipToState
        nillableDictionary["shipToZip"] = self.shipToZip
        nillableDictionary["shipToCountry"] = self.shipToCountry
        nillableDictionary["shipToPhone"] = self.shipToPhone
        nillableDictionary["shipToEmail"] = self.shipToEmail
        nillableDictionary["returnOrderStatus"] = self.returnOrderStatus
        nillableDictionary["returnReason"] = self.returnReason
        nillableDictionary["returnCategory"] = self.returnCategory
        nillableDictionary["returnInstructions"] = self.returnInstructions
        nillableDictionary["returnOrderLineItemList"] = self.returnOrderLineItemList?.encodeToJSON()
        nillableDictionary["customFields"] = self.customFields?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
