//
// ReturnOrderLineDetails.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class ReturnOrderLineDetails: JSONEncodable {
    public var id: Int32?
    public var createDate: NSDate?
    public var modifyDate: NSDate?
    public var lobId: Int32?
    public var warehouseId: Int32?
    public var returnOrderId: Int32?
    public var returnOrderLineId: Int32?
    public var sku: String?
    public var quantityReturned: Int32?
    public var warehouseLocationId: Int32?
    public var returnInspectionStatus: String?
    public var returnItemReceiptId: Int32?
    public var customFields: [String:AnyObject]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["createDate"] = self.createDate?.encodeToJSON()
        nillableDictionary["modifyDate"] = self.modifyDate?.encodeToJSON()
        nillableDictionary["lobId"] = self.lobId?.encodeToJSON()
        nillableDictionary["warehouseId"] = self.warehouseId?.encodeToJSON()
        nillableDictionary["returnOrderId"] = self.returnOrderId?.encodeToJSON()
        nillableDictionary["returnOrderLineId"] = self.returnOrderLineId?.encodeToJSON()
        nillableDictionary["sku"] = self.sku
        nillableDictionary["quantityReturned"] = self.quantityReturned?.encodeToJSON()
        nillableDictionary["warehouseLocationId"] = self.warehouseLocationId?.encodeToJSON()
        nillableDictionary["returnInspectionStatus"] = self.returnInspectionStatus
        nillableDictionary["returnItemReceiptId"] = self.returnItemReceiptId?.encodeToJSON()
        nillableDictionary["customFields"] = self.customFields?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
