//
// Work.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation


public class Work: JSONEncodable {
    public var id: Int32?
    public var sourceWarehouseId: Int32?
    public var sourceBuildingId: Int32?
    public var sourceLocation: String?
    public var destinationWarehouseId: Int32?
    public var destinationBuildingId: Int32?
    public var destinationLocation: String?
    public var type: String?
    public var createDate: NSDate?
    public var modifyDate: NSDate?
    public var priorityCode: Int32?
    public var userDefinedMessage: String?
    public var status: String?
    public var userId: Int32?
    public var lobId: Int32?
    public var workBatchId: Int32?
    public var customFields: [String:AnyObject]?

    public init() {}

    // MARK: JSONEncodable
    func encodeToJSON() -> AnyObject {
        var nillableDictionary = [String:AnyObject?]()
        nillableDictionary["id"] = self.id?.encodeToJSON()
        nillableDictionary["sourceWarehouseId"] = self.sourceWarehouseId?.encodeToJSON()
        nillableDictionary["sourceBuildingId"] = self.sourceBuildingId?.encodeToJSON()
        nillableDictionary["sourceLocation"] = self.sourceLocation
        nillableDictionary["destinationWarehouseId"] = self.destinationWarehouseId?.encodeToJSON()
        nillableDictionary["destinationBuildingId"] = self.destinationBuildingId?.encodeToJSON()
        nillableDictionary["destinationLocation"] = self.destinationLocation
        nillableDictionary["type"] = self.type
        nillableDictionary["createDate"] = self.createDate?.encodeToJSON()
        nillableDictionary["modifyDate"] = self.modifyDate?.encodeToJSON()
        nillableDictionary["priorityCode"] = self.priorityCode?.encodeToJSON()
        nillableDictionary["userDefinedMessage"] = self.userDefinedMessage
        nillableDictionary["status"] = self.status
        nillableDictionary["userId"] = self.userId?.encodeToJSON()
        nillableDictionary["lobId"] = self.lobId?.encodeToJSON()
        nillableDictionary["workBatchId"] = self.workBatchId?.encodeToJSON()
        nillableDictionary["customFields"] = self.customFields?.encodeToJSON()
        let dictionary: [String:AnyObject] = APIHelper.rejectNil(nillableDictionary) ?? [:]
        return dictionary
    }
}
