//
// ItemLegacyLowStockContactAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class ItemLegacyLowStockContactAPI: APIBase {
    /**
     
     Search itemLegacyLowStockContacts
     
     - parameter searchText: (query) Search text, used to filter results. (optional)
     - parameter page: (query) Result page number.  Defaults to 1. (optional)
     - parameter limit: (query) Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getItemLegacyLowStockContactBySearchText(searchText searchText: String?, page: Int?, limit: Int?, completion: ((data: [ItemLegacyLowStockContact]?, error: ErrorType?) -> Void)) {
        getItemLegacyLowStockContactBySearchTextWithRequestBuilder(searchText: searchText, page: page, limit: limit).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Search itemLegacyLowStockContacts
     
     - GET /beta/itemLegacyLowStockContact/search
     - Returns the list of itemLegacyLowStockContacts that match the given searchText.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{contentType=application/json, example=[ {
  "id" : 123,
  "label" : "aeiou"
} ]}]
     
     - parameter searchText: (query) Search text, used to filter results. (optional)
     - parameter page: (query) Result page number.  Defaults to 1. (optional)
     - parameter limit: (query) Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)

     - returns: RequestBuilder<[ItemLegacyLowStockContact]> 
     */
    public class func getItemLegacyLowStockContactBySearchTextWithRequestBuilder(searchText searchText: String?, page: Int?, limit: Int?) -> RequestBuilder<[ItemLegacyLowStockContact]> {
        let path = "/beta/itemLegacyLowStockContact/search"
        let URLString = InfoplusAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "searchText": searchText,
            "page": page,
            "limit": limit
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<[ItemLegacyLowStockContact]>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
    }

    /**
     
     Get an itemLegacyLowStockContact by id
     
     - parameter itemLegacyLowStockContactId: (path) Id of itemLegacyLowStockContact to be returned. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getTranslateLowStockContactById(itemLegacyLowStockContactId itemLegacyLowStockContactId: String, completion: ((data: ItemLegacyLowStockContact?, error: ErrorType?) -> Void)) {
        getTranslateLowStockContactByIdWithRequestBuilder(itemLegacyLowStockContactId: itemLegacyLowStockContactId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Get an itemLegacyLowStockContact by id
     
     - GET /beta/itemLegacyLowStockContact/{itemLegacyLowStockContactId}
     - Returns the itemLegacyLowStockContact identified by the specified id.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{contentType=application/json, example={
  "id" : 123,
  "label" : "aeiou"
}}]
     
     - parameter itemLegacyLowStockContactId: (path) Id of itemLegacyLowStockContact to be returned. 

     - returns: RequestBuilder<ItemLegacyLowStockContact> 
     */
    public class func getTranslateLowStockContactByIdWithRequestBuilder(itemLegacyLowStockContactId itemLegacyLowStockContactId: String) -> RequestBuilder<ItemLegacyLowStockContact> {
        var path = "/beta/itemLegacyLowStockContact/{itemLegacyLowStockContactId}"
        path = path.stringByReplacingOccurrencesOfString("{itemLegacyLowStockContactId}", withString: "\(itemLegacyLowStockContactId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<ItemLegacyLowStockContact>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

}
