//
// ItemReceiptActivityAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class ItemReceiptActivityAPI: APIBase {
    /**
     Create an itemReceiptActivity
     
     - parameter body: (body) ItemReceiptActivity to be inserted. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addItemReceiptActivity(body body: ItemReceiptActivity, completion: ((data: ItemReceiptActivity?, error: ErrorType?) -> Void)) {
        addItemReceiptActivityWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Create an itemReceiptActivity
     - POST /beta/itemReceiptActivity
     - Inserts a new itemReceiptActivity using the specified data.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{contentType=application/json, example={
  "receiptNumberOfPallets" : 7,
  "itemSector" : "itemSector",
  "alcoholTypeId" : 6,
  "vendorComplianceSurveyAnswer15" : "vendorComplianceSurveyAnswer15",
  "vendorComplianceSurveyAnswer14" : "vendorComplianceSurveyAnswer14",
  "vendorComplianceSurveyAnswer13" : "vendorComplianceSurveyAnswer13",
  "receiptDistributionDate" : "2000-01-23T04:56:07.000+00:00",
  "vendorComplianceSurveyAnswer12" : "vendorComplianceSurveyAnswer12",
  "vendorComplianceSurveyAnswer11" : "vendorComplianceSurveyAnswer11",
  "vendorComplianceSurveyAnswer10" : "vendorComplianceSurveyAnswer10",
  "vendorComplianceSurveyAnswer6" : "vendorComplianceSurveyAnswer6",
  "itemVendorSku" : "itemVendorSku",
  "itemSummaryCodeName" : "itemSummaryCodeName",
  "vendorComplianceSurveyAnswer5" : "vendorComplianceSurveyAnswer5",
  "alcoholContainerVolume" : 1,
  "vendorComplianceSurveyAnswer4" : "vendorComplianceSurveyAnswer4",
  "vendorComplianceSurveyAnswer3" : "vendorComplianceSurveyAnswer3",
  "poNo" : "poNo",
  "vendorComplianceSurveyAnswer9" : "vendorComplianceSurveyAnswer9",
  "vendorComplianceSurveyAnswer8" : "vendorComplianceSurveyAnswer8",
  "alcoholContent" : 3.557195227068097320710649000830017030239105224609375,
  "vendorComplianceSurveyAnswer7" : "vendorComplianceSurveyAnswer7",
  "receiptUnitsPerInnerPack" : 5,
  "receiptReceiveDate" : "2000-01-23T04:56:07.000+00:00",
  "receiptUnitsPerCase" : 2,
  "id" : 0,
  "receiptProductionLot" : "receiptProductionLot",
  "sku" : "sku",
  "vendorComplianceSurveyAnswer2" : "vendorComplianceSurveyAnswer2",
  "alcoholState" : "alcoholState",
  "receiptReceivedBy" : "receiptReceivedBy",
  "vendorComplianceSurveyAnswer1" : "vendorComplianceSurveyAnswer1",
  "alcoholTypeName" : "alcoholTypeName",
  "lobId" : 1,
  "receivedNumberOfCases" : 1,
  "receiptUnitCode" : 6,
  "receiptNumberOfInnerPack" : 2,
  "modifyDate" : "2000-01-23T04:56:07.000+00:00",
  "receiptType" : "receiptType",
  "itemProductCodeName" : "itemProductCodeName",
  "itemProductCode" : 8,
  "receiptUnitsPerWrap" : 5,
  "receiptUnitCodeText" : "receiptUnitCodeText",
  "receiptNumberOfCases" : 4,
  "itemAccountCodeName" : "itemAccountCodeName",
  "alcoholContainerName" : "alcoholContainerName",
  "itemSubGroupName" : "itemSubGroupName",
  "alcoholCountryId" : 2,
  "alcoholContainerId" : 6,
  "itemId" : 9,
  "itemMajorGroup" : 9,
  "chargeRate" : 6.87805222012787620400331434211693704128265380859375,
  "alcoholUPCCode" : "alcoholUPCCode",
  "warehouseId" : 5,
  "itemUPC" : "itemUPC",
  "itemSummaryCode" : 9,
  "alcoholRegion" : "alcoholRegion",
  "extendedCharge" : 5.94489560761401580890606055618263781070709228515625,
  "receiptStatus" : "receiptStatus",
  "receiptProductIdTag" : "receiptProductIdTag",
  "receiptModifyDate" : "2000-01-23T04:56:07.000+00:00",
  "alcoholSCCCode" : "alcoholSCCCode",
  "customFields" : {
    "key" : "{}"
  },
  "receiptWrapUnitWeight" : 1.173074250955943309548956676735542714595794677734375,
  "receiptRevisionDate" : "receiptRevisionDate",
  "receiptUnitsPerPallet" : 7,
  "warehouseName" : "warehouseName",
  "receivedNumberOfPallets" : 1,
  "receiptStatusName" : "receiptStatusName",
  "receiptEnteredBy" : "receiptEnteredBy",
  "receiptWrapCodeText" : "receiptWrapCodeText",
  "alcoholBrand" : "alcoholBrand",
  "receiptCaseWeight" : 4.9652184929849543237878606305457651615142822265625,
  "receiptReceiveQuantity" : 3,
  "createDate" : "2000-01-23T04:56:07.000+00:00",
  "alcoholVintageYear" : "alcoholVintageYear",
  "receiptVendor" : 9,
  "alcoholCountryName" : "alcoholCountryName",
  "alcoholNABCACode" : "alcoholNABCACode",
  "alcoholUNIMERCCode" : "alcoholUNIMERCCode",
  "receiptWrapCode" : 7,
  "vendorComplianceSurveyAnswer20" : "vendorComplianceSurveyAnswer20",
  "billingQuantity" : 6.77832496304801335185175048536621034145355224609375,
  "itemAccountCode" : "itemAccountCode",
  "receiptASNCreateDate" : "2000-01-23T04:56:07.000+00:00",
  "vendorComplianceSurveyAnswer19" : "vendorComplianceSurveyAnswer19",
  "vendorComplianceSurveyAnswer18" : "vendorComplianceSurveyAnswer18",
  "vendorComplianceSurveyAnswer17" : "vendorComplianceSurveyAnswer17",
  "vendorComplianceSurveyAnswer16" : "vendorComplianceSurveyAnswer16",
  "receivedNumberOfInnerPack" : 1,
  "itemSubGroup" : 6,
  "itemReceiptId" : 6,
  "itemMajorGroupName" : "itemMajorGroupName"
}}]
     
     - parameter body: (body) ItemReceiptActivity to be inserted. 

     - returns: RequestBuilder<ItemReceiptActivity> 
     */
    public class func addItemReceiptActivityWithRequestBuilder(body body: ItemReceiptActivity) -> RequestBuilder<ItemReceiptActivity> {
        let path = "/beta/itemReceiptActivity"
        let URLString = InfoplusAPI.basePath + path
        let parameters = body.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<ItemReceiptActivity>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Add new audit for an itemReceiptActivity
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to add an audit to 
     - parameter itemReceiptActivityAudit: (path) The audit to add 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addItemReceiptActivityAudit(itemReceiptActivityId itemReceiptActivityId: Int32, itemReceiptActivityAudit: String, completion: ((error: ErrorType?) -> Void)) {
        addItemReceiptActivityAuditWithRequestBuilder(itemReceiptActivityId: itemReceiptActivityId, itemReceiptActivityAudit: itemReceiptActivityAudit).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Add new audit for an itemReceiptActivity
     - PUT /beta/itemReceiptActivity/{itemReceiptActivityId}/audit/{itemReceiptActivityAudit}
     - Adds an audit to an existing itemReceiptActivity.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to add an audit to 
     - parameter itemReceiptActivityAudit: (path) The audit to add 

     - returns: RequestBuilder<Void> 
     */
    public class func addItemReceiptActivityAuditWithRequestBuilder(itemReceiptActivityId itemReceiptActivityId: Int32, itemReceiptActivityAudit: String) -> RequestBuilder<Void> {
        var path = "/beta/itemReceiptActivity/{itemReceiptActivityId}/audit/{itemReceiptActivityAudit}"
        path = path.stringByReplacingOccurrencesOfString("{itemReceiptActivityId}", withString: "\(itemReceiptActivityId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{itemReceiptActivityAudit}", withString: "\(itemReceiptActivityAudit)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Attach a file to an itemReceiptActivity
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to add a file to 
     - parameter fileName: (path) Name of file 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addItemReceiptActivityFile(itemReceiptActivityId itemReceiptActivityId: Int32, fileName: String, completion: ((error: ErrorType?) -> Void)) {
        addItemReceiptActivityFileWithRequestBuilder(itemReceiptActivityId: itemReceiptActivityId, fileName: fileName).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Attach a file to an itemReceiptActivity
     - POST /beta/itemReceiptActivity/{itemReceiptActivityId}/file/{fileName}
     - Adds a file to an existing itemReceiptActivity.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to add a file to 
     - parameter fileName: (path) Name of file 

     - returns: RequestBuilder<Void> 
     */
    public class func addItemReceiptActivityFileWithRequestBuilder(itemReceiptActivityId itemReceiptActivityId: Int32, fileName: String) -> RequestBuilder<Void> {
        var path = "/beta/itemReceiptActivity/{itemReceiptActivityId}/file/{fileName}"
        path = path.stringByReplacingOccurrencesOfString("{itemReceiptActivityId}", withString: "\(itemReceiptActivityId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{fileName}", withString: "\(fileName)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Attach a file to an itemReceiptActivity by URL.
     
     - parameter body: (body) The url and optionly fileName to be used. 
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to add an file to 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addItemReceiptActivityFileByURL(body body: RecordFile, itemReceiptActivityId: Int32, completion: ((error: ErrorType?) -> Void)) {
        addItemReceiptActivityFileByURLWithRequestBuilder(body: body, itemReceiptActivityId: itemReceiptActivityId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Attach a file to an itemReceiptActivity by URL.
     - POST /beta/itemReceiptActivity/{itemReceiptActivityId}/file
     - Adds a file to an existing itemReceiptActivity by URL.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter body: (body) The url and optionly fileName to be used. 
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to add an file to 

     - returns: RequestBuilder<Void> 
     */
    public class func addItemReceiptActivityFileByURLWithRequestBuilder(body body: RecordFile, itemReceiptActivityId: Int32) -> RequestBuilder<Void> {
        var path = "/beta/itemReceiptActivity/{itemReceiptActivityId}/file"
        path = path.stringByReplacingOccurrencesOfString("{itemReceiptActivityId}", withString: "\(itemReceiptActivityId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path
        let parameters = body.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Add new tags for an itemReceiptActivity.
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to add a tag to 
     - parameter itemReceiptActivityTag: (path) The tag to add 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addItemReceiptActivityTag(itemReceiptActivityId itemReceiptActivityId: Int32, itemReceiptActivityTag: String, completion: ((error: ErrorType?) -> Void)) {
        addItemReceiptActivityTagWithRequestBuilder(itemReceiptActivityId: itemReceiptActivityId, itemReceiptActivityTag: itemReceiptActivityTag).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Add new tags for an itemReceiptActivity.
     - PUT /beta/itemReceiptActivity/{itemReceiptActivityId}/tag/{itemReceiptActivityTag}
     - Adds a tag to an existing itemReceiptActivity.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to add a tag to 
     - parameter itemReceiptActivityTag: (path) The tag to add 

     - returns: RequestBuilder<Void> 
     */
    public class func addItemReceiptActivityTagWithRequestBuilder(itemReceiptActivityId itemReceiptActivityId: Int32, itemReceiptActivityTag: String) -> RequestBuilder<Void> {
        var path = "/beta/itemReceiptActivity/{itemReceiptActivityId}/tag/{itemReceiptActivityTag}"
        path = path.stringByReplacingOccurrencesOfString("{itemReceiptActivityId}", withString: "\(itemReceiptActivityId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{itemReceiptActivityTag}", withString: "\(itemReceiptActivityTag)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Delete an itemReceiptActivity
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to be deleted. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteItemReceiptActivity(itemReceiptActivityId itemReceiptActivityId: Int32, completion: ((error: ErrorType?) -> Void)) {
        deleteItemReceiptActivityWithRequestBuilder(itemReceiptActivityId: itemReceiptActivityId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Delete an itemReceiptActivity
     - DELETE /beta/itemReceiptActivity/{itemReceiptActivityId}
     - Deletes the itemReceiptActivity identified by the specified id.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to be deleted. 

     - returns: RequestBuilder<Void> 
     */
    public class func deleteItemReceiptActivityWithRequestBuilder(itemReceiptActivityId itemReceiptActivityId: Int32) -> RequestBuilder<Void> {
        var path = "/beta/itemReceiptActivity/{itemReceiptActivityId}"
        path = path.stringByReplacingOccurrencesOfString("{itemReceiptActivityId}", withString: "\(itemReceiptActivityId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Delete a file for an itemReceiptActivity.
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to remove file from 
     - parameter fileId: (path) Id of the file to delete 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteItemReceiptActivityFile(itemReceiptActivityId itemReceiptActivityId: Int32, fileId: Int32, completion: ((error: ErrorType?) -> Void)) {
        deleteItemReceiptActivityFileWithRequestBuilder(itemReceiptActivityId: itemReceiptActivityId, fileId: fileId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Delete a file for an itemReceiptActivity.
     - DELETE /beta/itemReceiptActivity/{itemReceiptActivityId}/file/{fileId}
     - Deletes an existing itemReceiptActivity file using the specified data.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to remove file from 
     - parameter fileId: (path) Id of the file to delete 

     - returns: RequestBuilder<Void> 
     */
    public class func deleteItemReceiptActivityFileWithRequestBuilder(itemReceiptActivityId itemReceiptActivityId: Int32, fileId: Int32) -> RequestBuilder<Void> {
        var path = "/beta/itemReceiptActivity/{itemReceiptActivityId}/file/{fileId}"
        path = path.stringByReplacingOccurrencesOfString("{itemReceiptActivityId}", withString: "\(itemReceiptActivityId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{fileId}", withString: "\(fileId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Delete a tag for an itemReceiptActivity.
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to remove tag from 
     - parameter itemReceiptActivityTag: (path) The tag to delete 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteItemReceiptActivityTag(itemReceiptActivityId itemReceiptActivityId: Int32, itemReceiptActivityTag: String, completion: ((error: ErrorType?) -> Void)) {
        deleteItemReceiptActivityTagWithRequestBuilder(itemReceiptActivityId: itemReceiptActivityId, itemReceiptActivityTag: itemReceiptActivityTag).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Delete a tag for an itemReceiptActivity.
     - DELETE /beta/itemReceiptActivity/{itemReceiptActivityId}/tag/{itemReceiptActivityTag}
     - Deletes an existing itemReceiptActivity tag using the specified data.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to remove tag from 
     - parameter itemReceiptActivityTag: (path) The tag to delete 

     - returns: RequestBuilder<Void> 
     */
    public class func deleteItemReceiptActivityTagWithRequestBuilder(itemReceiptActivityId itemReceiptActivityId: Int32, itemReceiptActivityTag: String) -> RequestBuilder<Void> {
        var path = "/beta/itemReceiptActivity/{itemReceiptActivityId}/tag/{itemReceiptActivityTag}"
        path = path.stringByReplacingOccurrencesOfString("{itemReceiptActivityId}", withString: "\(itemReceiptActivityId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{itemReceiptActivityTag}", withString: "\(itemReceiptActivityTag)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get a duplicated an itemReceiptActivity by id
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to be duplicated. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getDuplicateItemReceiptActivityById(itemReceiptActivityId itemReceiptActivityId: Int32, completion: ((data: ItemReceiptActivity?, error: ErrorType?) -> Void)) {
        getDuplicateItemReceiptActivityByIdWithRequestBuilder(itemReceiptActivityId: itemReceiptActivityId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get a duplicated an itemReceiptActivity by id
     - GET /beta/itemReceiptActivity/duplicate/{itemReceiptActivityId}
     - Returns a duplicated itemReceiptActivity identified by the specified id.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{contentType=application/json, example={
  "receiptNumberOfPallets" : 7,
  "itemSector" : "itemSector",
  "alcoholTypeId" : 6,
  "vendorComplianceSurveyAnswer15" : "vendorComplianceSurveyAnswer15",
  "vendorComplianceSurveyAnswer14" : "vendorComplianceSurveyAnswer14",
  "vendorComplianceSurveyAnswer13" : "vendorComplianceSurveyAnswer13",
  "receiptDistributionDate" : "2000-01-23T04:56:07.000+00:00",
  "vendorComplianceSurveyAnswer12" : "vendorComplianceSurveyAnswer12",
  "vendorComplianceSurveyAnswer11" : "vendorComplianceSurveyAnswer11",
  "vendorComplianceSurveyAnswer10" : "vendorComplianceSurveyAnswer10",
  "vendorComplianceSurveyAnswer6" : "vendorComplianceSurveyAnswer6",
  "itemVendorSku" : "itemVendorSku",
  "itemSummaryCodeName" : "itemSummaryCodeName",
  "vendorComplianceSurveyAnswer5" : "vendorComplianceSurveyAnswer5",
  "alcoholContainerVolume" : 1,
  "vendorComplianceSurveyAnswer4" : "vendorComplianceSurveyAnswer4",
  "vendorComplianceSurveyAnswer3" : "vendorComplianceSurveyAnswer3",
  "poNo" : "poNo",
  "vendorComplianceSurveyAnswer9" : "vendorComplianceSurveyAnswer9",
  "vendorComplianceSurveyAnswer8" : "vendorComplianceSurveyAnswer8",
  "alcoholContent" : 3.557195227068097320710649000830017030239105224609375,
  "vendorComplianceSurveyAnswer7" : "vendorComplianceSurveyAnswer7",
  "receiptUnitsPerInnerPack" : 5,
  "receiptReceiveDate" : "2000-01-23T04:56:07.000+00:00",
  "receiptUnitsPerCase" : 2,
  "id" : 0,
  "receiptProductionLot" : "receiptProductionLot",
  "sku" : "sku",
  "vendorComplianceSurveyAnswer2" : "vendorComplianceSurveyAnswer2",
  "alcoholState" : "alcoholState",
  "receiptReceivedBy" : "receiptReceivedBy",
  "vendorComplianceSurveyAnswer1" : "vendorComplianceSurveyAnswer1",
  "alcoholTypeName" : "alcoholTypeName",
  "lobId" : 1,
  "receivedNumberOfCases" : 1,
  "receiptUnitCode" : 6,
  "receiptNumberOfInnerPack" : 2,
  "modifyDate" : "2000-01-23T04:56:07.000+00:00",
  "receiptType" : "receiptType",
  "itemProductCodeName" : "itemProductCodeName",
  "itemProductCode" : 8,
  "receiptUnitsPerWrap" : 5,
  "receiptUnitCodeText" : "receiptUnitCodeText",
  "receiptNumberOfCases" : 4,
  "itemAccountCodeName" : "itemAccountCodeName",
  "alcoholContainerName" : "alcoholContainerName",
  "itemSubGroupName" : "itemSubGroupName",
  "alcoholCountryId" : 2,
  "alcoholContainerId" : 6,
  "itemId" : 9,
  "itemMajorGroup" : 9,
  "chargeRate" : 6.87805222012787620400331434211693704128265380859375,
  "alcoholUPCCode" : "alcoholUPCCode",
  "warehouseId" : 5,
  "itemUPC" : "itemUPC",
  "itemSummaryCode" : 9,
  "alcoholRegion" : "alcoholRegion",
  "extendedCharge" : 5.94489560761401580890606055618263781070709228515625,
  "receiptStatus" : "receiptStatus",
  "receiptProductIdTag" : "receiptProductIdTag",
  "receiptModifyDate" : "2000-01-23T04:56:07.000+00:00",
  "alcoholSCCCode" : "alcoholSCCCode",
  "customFields" : {
    "key" : "{}"
  },
  "receiptWrapUnitWeight" : 1.173074250955943309548956676735542714595794677734375,
  "receiptRevisionDate" : "receiptRevisionDate",
  "receiptUnitsPerPallet" : 7,
  "warehouseName" : "warehouseName",
  "receivedNumberOfPallets" : 1,
  "receiptStatusName" : "receiptStatusName",
  "receiptEnteredBy" : "receiptEnteredBy",
  "receiptWrapCodeText" : "receiptWrapCodeText",
  "alcoholBrand" : "alcoholBrand",
  "receiptCaseWeight" : 4.9652184929849543237878606305457651615142822265625,
  "receiptReceiveQuantity" : 3,
  "createDate" : "2000-01-23T04:56:07.000+00:00",
  "alcoholVintageYear" : "alcoholVintageYear",
  "receiptVendor" : 9,
  "alcoholCountryName" : "alcoholCountryName",
  "alcoholNABCACode" : "alcoholNABCACode",
  "alcoholUNIMERCCode" : "alcoholUNIMERCCode",
  "receiptWrapCode" : 7,
  "vendorComplianceSurveyAnswer20" : "vendorComplianceSurveyAnswer20",
  "billingQuantity" : 6.77832496304801335185175048536621034145355224609375,
  "itemAccountCode" : "itemAccountCode",
  "receiptASNCreateDate" : "2000-01-23T04:56:07.000+00:00",
  "vendorComplianceSurveyAnswer19" : "vendorComplianceSurveyAnswer19",
  "vendorComplianceSurveyAnswer18" : "vendorComplianceSurveyAnswer18",
  "vendorComplianceSurveyAnswer17" : "vendorComplianceSurveyAnswer17",
  "vendorComplianceSurveyAnswer16" : "vendorComplianceSurveyAnswer16",
  "receivedNumberOfInnerPack" : 1,
  "itemSubGroup" : 6,
  "itemReceiptId" : 6,
  "itemMajorGroupName" : "itemMajorGroupName"
}}]
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to be duplicated. 

     - returns: RequestBuilder<ItemReceiptActivity> 
     */
    public class func getDuplicateItemReceiptActivityByIdWithRequestBuilder(itemReceiptActivityId itemReceiptActivityId: Int32) -> RequestBuilder<ItemReceiptActivity> {
        var path = "/beta/itemReceiptActivity/duplicate/{itemReceiptActivityId}"
        path = path.stringByReplacingOccurrencesOfString("{itemReceiptActivityId}", withString: "\(itemReceiptActivityId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<ItemReceiptActivity>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Search itemReceiptActivitys by filter
     
     - parameter filter: (query) Query string, used to filter results. (optional)
     - parameter page: (query) Result page number.  Defaults to 1. (optional)
     - parameter limit: (query) Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     - parameter sort: (query) Sort results by specified field. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getItemReceiptActivityByFilter(filter filter: String? = nil, page: Int32? = nil, limit: Int32? = nil, sort: String? = nil, completion: ((data: [ItemReceiptActivity]?, error: ErrorType?) -> Void)) {
        getItemReceiptActivityByFilterWithRequestBuilder(filter: filter, page: page, limit: limit, sort: sort).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Search itemReceiptActivitys by filter
     - GET /beta/itemReceiptActivity/search
     - Returns the list of itemReceiptActivitys that match the given filter.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{contentType=application/json, example=[ {
  "receiptNumberOfPallets" : 7,
  "itemSector" : "itemSector",
  "alcoholTypeId" : 6,
  "vendorComplianceSurveyAnswer15" : "vendorComplianceSurveyAnswer15",
  "vendorComplianceSurveyAnswer14" : "vendorComplianceSurveyAnswer14",
  "vendorComplianceSurveyAnswer13" : "vendorComplianceSurveyAnswer13",
  "receiptDistributionDate" : "2000-01-23T04:56:07.000+00:00",
  "vendorComplianceSurveyAnswer12" : "vendorComplianceSurveyAnswer12",
  "vendorComplianceSurveyAnswer11" : "vendorComplianceSurveyAnswer11",
  "vendorComplianceSurveyAnswer10" : "vendorComplianceSurveyAnswer10",
  "vendorComplianceSurveyAnswer6" : "vendorComplianceSurveyAnswer6",
  "itemVendorSku" : "itemVendorSku",
  "itemSummaryCodeName" : "itemSummaryCodeName",
  "vendorComplianceSurveyAnswer5" : "vendorComplianceSurveyAnswer5",
  "alcoholContainerVolume" : 1,
  "vendorComplianceSurveyAnswer4" : "vendorComplianceSurveyAnswer4",
  "vendorComplianceSurveyAnswer3" : "vendorComplianceSurveyAnswer3",
  "poNo" : "poNo",
  "vendorComplianceSurveyAnswer9" : "vendorComplianceSurveyAnswer9",
  "vendorComplianceSurveyAnswer8" : "vendorComplianceSurveyAnswer8",
  "alcoholContent" : 3.557195227068097320710649000830017030239105224609375,
  "vendorComplianceSurveyAnswer7" : "vendorComplianceSurveyAnswer7",
  "receiptUnitsPerInnerPack" : 5,
  "receiptReceiveDate" : "2000-01-23T04:56:07.000+00:00",
  "receiptUnitsPerCase" : 2,
  "id" : 0,
  "receiptProductionLot" : "receiptProductionLot",
  "sku" : "sku",
  "vendorComplianceSurveyAnswer2" : "vendorComplianceSurveyAnswer2",
  "alcoholState" : "alcoholState",
  "receiptReceivedBy" : "receiptReceivedBy",
  "vendorComplianceSurveyAnswer1" : "vendorComplianceSurveyAnswer1",
  "alcoholTypeName" : "alcoholTypeName",
  "lobId" : 1,
  "receivedNumberOfCases" : 1,
  "receiptUnitCode" : 6,
  "receiptNumberOfInnerPack" : 2,
  "modifyDate" : "2000-01-23T04:56:07.000+00:00",
  "receiptType" : "receiptType",
  "itemProductCodeName" : "itemProductCodeName",
  "itemProductCode" : 8,
  "receiptUnitsPerWrap" : 5,
  "receiptUnitCodeText" : "receiptUnitCodeText",
  "receiptNumberOfCases" : 4,
  "itemAccountCodeName" : "itemAccountCodeName",
  "alcoholContainerName" : "alcoholContainerName",
  "itemSubGroupName" : "itemSubGroupName",
  "alcoholCountryId" : 2,
  "alcoholContainerId" : 6,
  "itemId" : 9,
  "itemMajorGroup" : 9,
  "chargeRate" : 6.87805222012787620400331434211693704128265380859375,
  "alcoholUPCCode" : "alcoholUPCCode",
  "warehouseId" : 5,
  "itemUPC" : "itemUPC",
  "itemSummaryCode" : 9,
  "alcoholRegion" : "alcoholRegion",
  "extendedCharge" : 5.94489560761401580890606055618263781070709228515625,
  "receiptStatus" : "receiptStatus",
  "receiptProductIdTag" : "receiptProductIdTag",
  "receiptModifyDate" : "2000-01-23T04:56:07.000+00:00",
  "alcoholSCCCode" : "alcoholSCCCode",
  "customFields" : {
    "key" : "{}"
  },
  "receiptWrapUnitWeight" : 1.173074250955943309548956676735542714595794677734375,
  "receiptRevisionDate" : "receiptRevisionDate",
  "receiptUnitsPerPallet" : 7,
  "warehouseName" : "warehouseName",
  "receivedNumberOfPallets" : 1,
  "receiptStatusName" : "receiptStatusName",
  "receiptEnteredBy" : "receiptEnteredBy",
  "receiptWrapCodeText" : "receiptWrapCodeText",
  "alcoholBrand" : "alcoholBrand",
  "receiptCaseWeight" : 4.9652184929849543237878606305457651615142822265625,
  "receiptReceiveQuantity" : 3,
  "createDate" : "2000-01-23T04:56:07.000+00:00",
  "alcoholVintageYear" : "alcoholVintageYear",
  "receiptVendor" : 9,
  "alcoholCountryName" : "alcoholCountryName",
  "alcoholNABCACode" : "alcoholNABCACode",
  "alcoholUNIMERCCode" : "alcoholUNIMERCCode",
  "receiptWrapCode" : 7,
  "vendorComplianceSurveyAnswer20" : "vendorComplianceSurveyAnswer20",
  "billingQuantity" : 6.77832496304801335185175048536621034145355224609375,
  "itemAccountCode" : "itemAccountCode",
  "receiptASNCreateDate" : "2000-01-23T04:56:07.000+00:00",
  "vendorComplianceSurveyAnswer19" : "vendorComplianceSurveyAnswer19",
  "vendorComplianceSurveyAnswer18" : "vendorComplianceSurveyAnswer18",
  "vendorComplianceSurveyAnswer17" : "vendorComplianceSurveyAnswer17",
  "vendorComplianceSurveyAnswer16" : "vendorComplianceSurveyAnswer16",
  "receivedNumberOfInnerPack" : 1,
  "itemSubGroup" : 6,
  "itemReceiptId" : 6,
  "itemMajorGroupName" : "itemMajorGroupName"
}, {
  "receiptNumberOfPallets" : 7,
  "itemSector" : "itemSector",
  "alcoholTypeId" : 6,
  "vendorComplianceSurveyAnswer15" : "vendorComplianceSurveyAnswer15",
  "vendorComplianceSurveyAnswer14" : "vendorComplianceSurveyAnswer14",
  "vendorComplianceSurveyAnswer13" : "vendorComplianceSurveyAnswer13",
  "receiptDistributionDate" : "2000-01-23T04:56:07.000+00:00",
  "vendorComplianceSurveyAnswer12" : "vendorComplianceSurveyAnswer12",
  "vendorComplianceSurveyAnswer11" : "vendorComplianceSurveyAnswer11",
  "vendorComplianceSurveyAnswer10" : "vendorComplianceSurveyAnswer10",
  "vendorComplianceSurveyAnswer6" : "vendorComplianceSurveyAnswer6",
  "itemVendorSku" : "itemVendorSku",
  "itemSummaryCodeName" : "itemSummaryCodeName",
  "vendorComplianceSurveyAnswer5" : "vendorComplianceSurveyAnswer5",
  "alcoholContainerVolume" : 1,
  "vendorComplianceSurveyAnswer4" : "vendorComplianceSurveyAnswer4",
  "vendorComplianceSurveyAnswer3" : "vendorComplianceSurveyAnswer3",
  "poNo" : "poNo",
  "vendorComplianceSurveyAnswer9" : "vendorComplianceSurveyAnswer9",
  "vendorComplianceSurveyAnswer8" : "vendorComplianceSurveyAnswer8",
  "alcoholContent" : 3.557195227068097320710649000830017030239105224609375,
  "vendorComplianceSurveyAnswer7" : "vendorComplianceSurveyAnswer7",
  "receiptUnitsPerInnerPack" : 5,
  "receiptReceiveDate" : "2000-01-23T04:56:07.000+00:00",
  "receiptUnitsPerCase" : 2,
  "id" : 0,
  "receiptProductionLot" : "receiptProductionLot",
  "sku" : "sku",
  "vendorComplianceSurveyAnswer2" : "vendorComplianceSurveyAnswer2",
  "alcoholState" : "alcoholState",
  "receiptReceivedBy" : "receiptReceivedBy",
  "vendorComplianceSurveyAnswer1" : "vendorComplianceSurveyAnswer1",
  "alcoholTypeName" : "alcoholTypeName",
  "lobId" : 1,
  "receivedNumberOfCases" : 1,
  "receiptUnitCode" : 6,
  "receiptNumberOfInnerPack" : 2,
  "modifyDate" : "2000-01-23T04:56:07.000+00:00",
  "receiptType" : "receiptType",
  "itemProductCodeName" : "itemProductCodeName",
  "itemProductCode" : 8,
  "receiptUnitsPerWrap" : 5,
  "receiptUnitCodeText" : "receiptUnitCodeText",
  "receiptNumberOfCases" : 4,
  "itemAccountCodeName" : "itemAccountCodeName",
  "alcoholContainerName" : "alcoholContainerName",
  "itemSubGroupName" : "itemSubGroupName",
  "alcoholCountryId" : 2,
  "alcoholContainerId" : 6,
  "itemId" : 9,
  "itemMajorGroup" : 9,
  "chargeRate" : 6.87805222012787620400331434211693704128265380859375,
  "alcoholUPCCode" : "alcoholUPCCode",
  "warehouseId" : 5,
  "itemUPC" : "itemUPC",
  "itemSummaryCode" : 9,
  "alcoholRegion" : "alcoholRegion",
  "extendedCharge" : 5.94489560761401580890606055618263781070709228515625,
  "receiptStatus" : "receiptStatus",
  "receiptProductIdTag" : "receiptProductIdTag",
  "receiptModifyDate" : "2000-01-23T04:56:07.000+00:00",
  "alcoholSCCCode" : "alcoholSCCCode",
  "customFields" : {
    "key" : "{}"
  },
  "receiptWrapUnitWeight" : 1.173074250955943309548956676735542714595794677734375,
  "receiptRevisionDate" : "receiptRevisionDate",
  "receiptUnitsPerPallet" : 7,
  "warehouseName" : "warehouseName",
  "receivedNumberOfPallets" : 1,
  "receiptStatusName" : "receiptStatusName",
  "receiptEnteredBy" : "receiptEnteredBy",
  "receiptWrapCodeText" : "receiptWrapCodeText",
  "alcoholBrand" : "alcoholBrand",
  "receiptCaseWeight" : 4.9652184929849543237878606305457651615142822265625,
  "receiptReceiveQuantity" : 3,
  "createDate" : "2000-01-23T04:56:07.000+00:00",
  "alcoholVintageYear" : "alcoholVintageYear",
  "receiptVendor" : 9,
  "alcoholCountryName" : "alcoholCountryName",
  "alcoholNABCACode" : "alcoholNABCACode",
  "alcoholUNIMERCCode" : "alcoholUNIMERCCode",
  "receiptWrapCode" : 7,
  "vendorComplianceSurveyAnswer20" : "vendorComplianceSurveyAnswer20",
  "billingQuantity" : 6.77832496304801335185175048536621034145355224609375,
  "itemAccountCode" : "itemAccountCode",
  "receiptASNCreateDate" : "2000-01-23T04:56:07.000+00:00",
  "vendorComplianceSurveyAnswer19" : "vendorComplianceSurveyAnswer19",
  "vendorComplianceSurveyAnswer18" : "vendorComplianceSurveyAnswer18",
  "vendorComplianceSurveyAnswer17" : "vendorComplianceSurveyAnswer17",
  "vendorComplianceSurveyAnswer16" : "vendorComplianceSurveyAnswer16",
  "receivedNumberOfInnerPack" : 1,
  "itemSubGroup" : 6,
  "itemReceiptId" : 6,
  "itemMajorGroupName" : "itemMajorGroupName"
} ]}]
     
     - parameter filter: (query) Query string, used to filter results. (optional)
     - parameter page: (query) Result page number.  Defaults to 1. (optional)
     - parameter limit: (query) Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     - parameter sort: (query) Sort results by specified field. (optional)

     - returns: RequestBuilder<[ItemReceiptActivity]> 
     */
    public class func getItemReceiptActivityByFilterWithRequestBuilder(filter filter: String? = nil, page: Int32? = nil, limit: Int32? = nil, sort: String? = nil) -> RequestBuilder<[ItemReceiptActivity]> {
        let path = "/beta/itemReceiptActivity/search"
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "filter": filter,
            "page": page?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
            "sort": sort
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[ItemReceiptActivity]>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Get an itemReceiptActivity by id
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to be returned. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getItemReceiptActivityById(itemReceiptActivityId itemReceiptActivityId: Int32, completion: ((data: ItemReceiptActivity?, error: ErrorType?) -> Void)) {
        getItemReceiptActivityByIdWithRequestBuilder(itemReceiptActivityId: itemReceiptActivityId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get an itemReceiptActivity by id
     - GET /beta/itemReceiptActivity/{itemReceiptActivityId}
     - Returns the itemReceiptActivity identified by the specified id.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{contentType=application/json, example={
  "receiptNumberOfPallets" : 7,
  "itemSector" : "itemSector",
  "alcoholTypeId" : 6,
  "vendorComplianceSurveyAnswer15" : "vendorComplianceSurveyAnswer15",
  "vendorComplianceSurveyAnswer14" : "vendorComplianceSurveyAnswer14",
  "vendorComplianceSurveyAnswer13" : "vendorComplianceSurveyAnswer13",
  "receiptDistributionDate" : "2000-01-23T04:56:07.000+00:00",
  "vendorComplianceSurveyAnswer12" : "vendorComplianceSurveyAnswer12",
  "vendorComplianceSurveyAnswer11" : "vendorComplianceSurveyAnswer11",
  "vendorComplianceSurveyAnswer10" : "vendorComplianceSurveyAnswer10",
  "vendorComplianceSurveyAnswer6" : "vendorComplianceSurveyAnswer6",
  "itemVendorSku" : "itemVendorSku",
  "itemSummaryCodeName" : "itemSummaryCodeName",
  "vendorComplianceSurveyAnswer5" : "vendorComplianceSurveyAnswer5",
  "alcoholContainerVolume" : 1,
  "vendorComplianceSurveyAnswer4" : "vendorComplianceSurveyAnswer4",
  "vendorComplianceSurveyAnswer3" : "vendorComplianceSurveyAnswer3",
  "poNo" : "poNo",
  "vendorComplianceSurveyAnswer9" : "vendorComplianceSurveyAnswer9",
  "vendorComplianceSurveyAnswer8" : "vendorComplianceSurveyAnswer8",
  "alcoholContent" : 3.557195227068097320710649000830017030239105224609375,
  "vendorComplianceSurveyAnswer7" : "vendorComplianceSurveyAnswer7",
  "receiptUnitsPerInnerPack" : 5,
  "receiptReceiveDate" : "2000-01-23T04:56:07.000+00:00",
  "receiptUnitsPerCase" : 2,
  "id" : 0,
  "receiptProductionLot" : "receiptProductionLot",
  "sku" : "sku",
  "vendorComplianceSurveyAnswer2" : "vendorComplianceSurveyAnswer2",
  "alcoholState" : "alcoholState",
  "receiptReceivedBy" : "receiptReceivedBy",
  "vendorComplianceSurveyAnswer1" : "vendorComplianceSurveyAnswer1",
  "alcoholTypeName" : "alcoholTypeName",
  "lobId" : 1,
  "receivedNumberOfCases" : 1,
  "receiptUnitCode" : 6,
  "receiptNumberOfInnerPack" : 2,
  "modifyDate" : "2000-01-23T04:56:07.000+00:00",
  "receiptType" : "receiptType",
  "itemProductCodeName" : "itemProductCodeName",
  "itemProductCode" : 8,
  "receiptUnitsPerWrap" : 5,
  "receiptUnitCodeText" : "receiptUnitCodeText",
  "receiptNumberOfCases" : 4,
  "itemAccountCodeName" : "itemAccountCodeName",
  "alcoholContainerName" : "alcoholContainerName",
  "itemSubGroupName" : "itemSubGroupName",
  "alcoholCountryId" : 2,
  "alcoholContainerId" : 6,
  "itemId" : 9,
  "itemMajorGroup" : 9,
  "chargeRate" : 6.87805222012787620400331434211693704128265380859375,
  "alcoholUPCCode" : "alcoholUPCCode",
  "warehouseId" : 5,
  "itemUPC" : "itemUPC",
  "itemSummaryCode" : 9,
  "alcoholRegion" : "alcoholRegion",
  "extendedCharge" : 5.94489560761401580890606055618263781070709228515625,
  "receiptStatus" : "receiptStatus",
  "receiptProductIdTag" : "receiptProductIdTag",
  "receiptModifyDate" : "2000-01-23T04:56:07.000+00:00",
  "alcoholSCCCode" : "alcoholSCCCode",
  "customFields" : {
    "key" : "{}"
  },
  "receiptWrapUnitWeight" : 1.173074250955943309548956676735542714595794677734375,
  "receiptRevisionDate" : "receiptRevisionDate",
  "receiptUnitsPerPallet" : 7,
  "warehouseName" : "warehouseName",
  "receivedNumberOfPallets" : 1,
  "receiptStatusName" : "receiptStatusName",
  "receiptEnteredBy" : "receiptEnteredBy",
  "receiptWrapCodeText" : "receiptWrapCodeText",
  "alcoholBrand" : "alcoholBrand",
  "receiptCaseWeight" : 4.9652184929849543237878606305457651615142822265625,
  "receiptReceiveQuantity" : 3,
  "createDate" : "2000-01-23T04:56:07.000+00:00",
  "alcoholVintageYear" : "alcoholVintageYear",
  "receiptVendor" : 9,
  "alcoholCountryName" : "alcoholCountryName",
  "alcoholNABCACode" : "alcoholNABCACode",
  "alcoholUNIMERCCode" : "alcoholUNIMERCCode",
  "receiptWrapCode" : 7,
  "vendorComplianceSurveyAnswer20" : "vendorComplianceSurveyAnswer20",
  "billingQuantity" : 6.77832496304801335185175048536621034145355224609375,
  "itemAccountCode" : "itemAccountCode",
  "receiptASNCreateDate" : "2000-01-23T04:56:07.000+00:00",
  "vendorComplianceSurveyAnswer19" : "vendorComplianceSurveyAnswer19",
  "vendorComplianceSurveyAnswer18" : "vendorComplianceSurveyAnswer18",
  "vendorComplianceSurveyAnswer17" : "vendorComplianceSurveyAnswer17",
  "vendorComplianceSurveyAnswer16" : "vendorComplianceSurveyAnswer16",
  "receivedNumberOfInnerPack" : 1,
  "itemSubGroup" : 6,
  "itemReceiptId" : 6,
  "itemMajorGroupName" : "itemMajorGroupName"
}}]
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to be returned. 

     - returns: RequestBuilder<ItemReceiptActivity> 
     */
    public class func getItemReceiptActivityByIdWithRequestBuilder(itemReceiptActivityId itemReceiptActivityId: Int32) -> RequestBuilder<ItemReceiptActivity> {
        var path = "/beta/itemReceiptActivity/{itemReceiptActivityId}"
        path = path.stringByReplacingOccurrencesOfString("{itemReceiptActivityId}", withString: "\(itemReceiptActivityId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<ItemReceiptActivity>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get the files for an itemReceiptActivity.
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to get files for 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getItemReceiptActivityFiles(itemReceiptActivityId itemReceiptActivityId: Int32, completion: ((error: ErrorType?) -> Void)) {
        getItemReceiptActivityFilesWithRequestBuilder(itemReceiptActivityId: itemReceiptActivityId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Get the files for an itemReceiptActivity.
     - GET /beta/itemReceiptActivity/{itemReceiptActivityId}/file
     - Get all existing itemReceiptActivity files.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to get files for 

     - returns: RequestBuilder<Void> 
     */
    public class func getItemReceiptActivityFilesWithRequestBuilder(itemReceiptActivityId itemReceiptActivityId: Int32) -> RequestBuilder<Void> {
        var path = "/beta/itemReceiptActivity/{itemReceiptActivityId}/file"
        path = path.stringByReplacingOccurrencesOfString("{itemReceiptActivityId}", withString: "\(itemReceiptActivityId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get the tags for an itemReceiptActivity.
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to get tags for 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getItemReceiptActivityTags(itemReceiptActivityId itemReceiptActivityId: Int32, completion: ((error: ErrorType?) -> Void)) {
        getItemReceiptActivityTagsWithRequestBuilder(itemReceiptActivityId: itemReceiptActivityId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Get the tags for an itemReceiptActivity.
     - GET /beta/itemReceiptActivity/{itemReceiptActivityId}/tag
     - Get all existing itemReceiptActivity tags.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter itemReceiptActivityId: (path) Id of the itemReceiptActivity to get tags for 

     - returns: RequestBuilder<Void> 
     */
    public class func getItemReceiptActivityTagsWithRequestBuilder(itemReceiptActivityId itemReceiptActivityId: Int32) -> RequestBuilder<Void> {
        var path = "/beta/itemReceiptActivity/{itemReceiptActivityId}/tag"
        path = path.stringByReplacingOccurrencesOfString("{itemReceiptActivityId}", withString: "\(itemReceiptActivityId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Update an itemReceiptActivity
     
     - parameter body: (body) ItemReceiptActivity to be updated. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func updateItemReceiptActivity(body body: ItemReceiptActivity, completion: ((error: ErrorType?) -> Void)) {
        updateItemReceiptActivityWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Update an itemReceiptActivity
     - PUT /beta/itemReceiptActivity
     - Updates an existing itemReceiptActivity using the specified data.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter body: (body) ItemReceiptActivity to be updated. 

     - returns: RequestBuilder<Void> 
     */
    public class func updateItemReceiptActivityWithRequestBuilder(body body: ItemReceiptActivity) -> RequestBuilder<Void> {
        let path = "/beta/itemReceiptActivity"
        let URLString = InfoplusAPI.basePath + path
        let parameters = body.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
