//
// OrderLineAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class OrderLineAPI: APIBase {
    /**
     
     Search orderLines by filter
     
     - parameter filter: (query) Query string, used to filter results. (optional)
     - parameter page: (query) Result page number.  Defaults to 1. (optional)
     - parameter limit: (query) Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     - parameter sort: (query) Sort results by specified field. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getOrderLineByFilter(filter filter: String?, page: Int?, limit: Int?, sort: String?, completion: ((data: [OrderLine]?, error: ErrorType?) -> Void)) {
        getOrderLineByFilterWithRequestBuilder(filter: filter, page: page, limit: limit, sort: sort).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Search orderLines by filter
     
     - GET /v1.0/orderLine/search
     - Returns the list of orderLines that match the given filter.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{example=[ {
  "ncExtendedSell" : 1.3579000000000001069366817318950779736042022705078125,
  "sector" : "aeiou",
  "orderedQty" : 123,
  "revDate" : "aeiou",
  "id" : 123,
  "itemLegacyLowStockContactId" : 123,
  "vendorSKU" : "aeiou",
  "itemMajorGroupId" : 123,
  "unitCost" : 1.3579000000000001069366817318950779736042022705078125,
  "lobId" : 123,
  "extendedCost" : 1.3579000000000001069366817318950779736042022705078125,
  "extendedSell" : 1.3579000000000001069366817318950779736042022705078125,
  "allowedQty" : 123,
  "poNoId" : 123,
  "weightPerWrap" : 1.3579000000000001069366817318950779736042022705078125,
  "sku" : "aeiou",
  "distributionCode" : "aeiou",
  "upc" : "aeiou",
  "itemWeight" : 1.3579000000000001069366817318950779736042022705078125,
  "itemSummaryCodeId" : 123,
  "shippedQty" : 123,
  "unitSell" : 1.3579000000000001069366817318950779736042022705078125,
  "itemSubGroupId" : 123,
  "itemProductCodeId" : 123,
  "orderNo" : 1.3579000000000001069366817318950779736042022705078125,
  "backorderQty" : 123,
  "itemAccountCodeId" : 123,
  "orderSourceSKU" : "aeiou",
  "chargeCode" : "aeiou"
} ], contentType=application/json}]
     
     - parameter filter: (query) Query string, used to filter results. (optional)
     - parameter page: (query) Result page number.  Defaults to 1. (optional)
     - parameter limit: (query) Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     - parameter sort: (query) Sort results by specified field. (optional)

     - returns: RequestBuilder<[OrderLine]> 
     */
    public class func getOrderLineByFilterWithRequestBuilder(filter filter: String?, page: Int?, limit: Int?, sort: String?) -> RequestBuilder<[OrderLine]> {
        let path = "/v1.0/orderLine/search"
        let URLString = InfoplusAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "filter": filter,
            "page": page,
            "limit": limit,
            "sort": sort
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<[OrderLine]>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
    }

    /**
     
     Get an orderLine by id
     
     - parameter orderLineId: (path) Id of the orderLine to be returned. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getOrderLineById(orderLineId orderLineId: Int, completion: ((data: OrderLine?, error: ErrorType?) -> Void)) {
        getOrderLineByIdWithRequestBuilder(orderLineId: orderLineId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Get an orderLine by id
     
     - GET /v1.0/orderLine/{orderLineId}
     - Returns the orderLine identified by the specified id.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{example={
  "ncExtendedSell" : 1.3579000000000001069366817318950779736042022705078125,
  "sector" : "aeiou",
  "orderedQty" : 123,
  "revDate" : "aeiou",
  "id" : 123,
  "itemLegacyLowStockContactId" : 123,
  "vendorSKU" : "aeiou",
  "itemMajorGroupId" : 123,
  "unitCost" : 1.3579000000000001069366817318950779736042022705078125,
  "lobId" : 123,
  "extendedCost" : 1.3579000000000001069366817318950779736042022705078125,
  "extendedSell" : 1.3579000000000001069366817318950779736042022705078125,
  "allowedQty" : 123,
  "poNoId" : 123,
  "weightPerWrap" : 1.3579000000000001069366817318950779736042022705078125,
  "sku" : "aeiou",
  "distributionCode" : "aeiou",
  "upc" : "aeiou",
  "itemWeight" : 1.3579000000000001069366817318950779736042022705078125,
  "itemSummaryCodeId" : 123,
  "shippedQty" : 123,
  "unitSell" : 1.3579000000000001069366817318950779736042022705078125,
  "itemSubGroupId" : 123,
  "itemProductCodeId" : 123,
  "orderNo" : 1.3579000000000001069366817318950779736042022705078125,
  "backorderQty" : 123,
  "itemAccountCodeId" : 123,
  "orderSourceSKU" : "aeiou",
  "chargeCode" : "aeiou"
}, contentType=application/json}]
     
     - parameter orderLineId: (path) Id of the orderLine to be returned. 

     - returns: RequestBuilder<OrderLine> 
     */
    public class func getOrderLineByIdWithRequestBuilder(orderLineId orderLineId: Int) -> RequestBuilder<OrderLine> {
        var path = "/v1.0/orderLine/{orderLineId}"
        path = path.stringByReplacingOccurrencesOfString("{orderLineId}", withString: "\(orderLineId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<OrderLine>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

}
