//
// ParcelShipmentAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class ParcelShipmentAPI: APIBase {
    /**
     
     Search parcelShipments by filter
     
     - parameter filter: (query) Query string, used to filter results. (optional)
     - parameter page: (query) Result page number.  Defaults to 1. (optional)
     - parameter limit: (query) Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     - parameter sort: (query) Sort results by specified field. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getParcelShipmentByFilter(filter filter: String?, page: Int?, limit: Int?, sort: String?, completion: ((data: [ParcelShipment]?, error: ErrorType?) -> Void)) {
        getParcelShipmentByFilterWithRequestBuilder(filter: filter, page: page, limit: limit, sort: sort).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Search parcelShipments by filter
     
     - GET /v1.0/parcelShipment/search
     - Returns the list of parcelShipments that match the given filter.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{example=[ {
  "dim1In" : 1.3579000000000001069366817318950779736042022705078125,
  "trackingNo" : "aeiou",
  "residential" : true,
  "shipDate" : "2000-01-23T04:56:07.000+0000",
  "modifyDate" : "2000-01-23T04:56:07.000+0000",
  "id" : 123,
  "carrierServiceId" : 123,
  "chargedFreightAmount" : 1.3579000000000001069366817318950779736042022705078125,
  "shipped" : true,
  "manifestId" : 123,
  "licensePlateNumber" : "aeiou",
  "lobId" : 123,
  "createDate" : "2000-01-23T04:56:07.000+0000",
  "retailFreightAmount" : 1.3579000000000001069366817318950779736042022705078125,
  "dimWeight" : 1.3579000000000001069366817318950779736042022705078125,
  "billingOption" : "aeiou",
  "status" : "aeiou",
  "cartonNo" : 123,
  "numberOfCartons" : 123,
  "dim3In" : 1.3579000000000001069366817318950779736042022705078125,
  "parcelAccountNo" : "aeiou",
  "warehouseId" : 123,
  "orderNo" : 1.3579000000000001069366817318950779736042022705078125,
  "dim2In" : 1.3579000000000001069366817318950779736042022705078125,
  "estimatedZone" : "aeiou",
  "deliveredDate" : "2000-01-23T04:56:07.000+0000",
  "weightLbs" : 1.3579000000000001069366817318950779736042022705078125,
  "thirdPartyParcelAccountNo" : "aeiou",
  "publishedFreightAmount" : 1.3579000000000001069366817318950779736042022705078125
} ], contentType=application/json}]
     
     - parameter filter: (query) Query string, used to filter results. (optional)
     - parameter page: (query) Result page number.  Defaults to 1. (optional)
     - parameter limit: (query) Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     - parameter sort: (query) Sort results by specified field. (optional)

     - returns: RequestBuilder<[ParcelShipment]> 
     */
    public class func getParcelShipmentByFilterWithRequestBuilder(filter filter: String?, page: Int?, limit: Int?, sort: String?) -> RequestBuilder<[ParcelShipment]> {
        let path = "/v1.0/parcelShipment/search"
        let URLString = InfoplusAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "filter": filter,
            "page": page,
            "limit": limit,
            "sort": sort
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<[ParcelShipment]>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
    }

    /**
     
     Get a parcelShipment by id
     
     - parameter parcelShipmentId: (path) Id of the parcelShipment to be returned. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getParcelShipmentById(parcelShipmentId parcelShipmentId: Int, completion: ((data: ParcelShipment?, error: ErrorType?) -> Void)) {
        getParcelShipmentByIdWithRequestBuilder(parcelShipmentId: parcelShipmentId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Get a parcelShipment by id
     
     - GET /v1.0/parcelShipment/{parcelShipmentId}
     - Returns the parcelShipment identified by the specified id.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{example={
  "dim1In" : 1.3579000000000001069366817318950779736042022705078125,
  "trackingNo" : "aeiou",
  "residential" : true,
  "shipDate" : "2000-01-23T04:56:07.000+0000",
  "modifyDate" : "2000-01-23T04:56:07.000+0000",
  "id" : 123,
  "carrierServiceId" : 123,
  "chargedFreightAmount" : 1.3579000000000001069366817318950779736042022705078125,
  "shipped" : true,
  "manifestId" : 123,
  "licensePlateNumber" : "aeiou",
  "lobId" : 123,
  "createDate" : "2000-01-23T04:56:07.000+0000",
  "retailFreightAmount" : 1.3579000000000001069366817318950779736042022705078125,
  "dimWeight" : 1.3579000000000001069366817318950779736042022705078125,
  "billingOption" : "aeiou",
  "status" : "aeiou",
  "cartonNo" : 123,
  "numberOfCartons" : 123,
  "dim3In" : 1.3579000000000001069366817318950779736042022705078125,
  "parcelAccountNo" : "aeiou",
  "warehouseId" : 123,
  "orderNo" : 1.3579000000000001069366817318950779736042022705078125,
  "dim2In" : 1.3579000000000001069366817318950779736042022705078125,
  "estimatedZone" : "aeiou",
  "deliveredDate" : "2000-01-23T04:56:07.000+0000",
  "weightLbs" : 1.3579000000000001069366817318950779736042022705078125,
  "thirdPartyParcelAccountNo" : "aeiou",
  "publishedFreightAmount" : 1.3579000000000001069366817318950779736042022705078125
}, contentType=application/json}]
     
     - parameter parcelShipmentId: (path) Id of the parcelShipment to be returned. 

     - returns: RequestBuilder<ParcelShipment> 
     */
    public class func getParcelShipmentByIdWithRequestBuilder(parcelShipmentId parcelShipmentId: Int) -> RequestBuilder<ParcelShipment> {
        var path = "/v1.0/parcelShipment/{parcelShipmentId}"
        path = path.stringByReplacingOccurrencesOfString("{parcelShipmentId}", withString: "\(parcelShipmentId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<ParcelShipment>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

}
