//
// PerpetualInventoryLogAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class PerpetualInventoryLogAPI: APIBase {
    /**
     
     Add new audit for a perpetualInventoryLog
     
     - parameter perpetualInventoryLogId: (path) Id of the perpetualInventoryLog to add an audit to 
     - parameter perpetualInventoryLogAudit: (path) The audit to add 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addPerpetualInventoryLogAudit(perpetualInventoryLogId perpetualInventoryLogId: Int, perpetualInventoryLogAudit: String, completion: ((error: ErrorType?) -> Void)) {
        addPerpetualInventoryLogAuditWithRequestBuilder(perpetualInventoryLogId: perpetualInventoryLogId, perpetualInventoryLogAudit: perpetualInventoryLogAudit).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     Add new audit for a perpetualInventoryLog
     
     - PUT /beta/perpetualInventoryLog/{perpetualInventoryLogId}/audit/{perpetualInventoryLogAudit}
     - Adds an audit to an existing perpetualInventoryLog.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter perpetualInventoryLogId: (path) Id of the perpetualInventoryLog to add an audit to 
     - parameter perpetualInventoryLogAudit: (path) The audit to add 

     - returns: RequestBuilder<Void> 
     */
    public class func addPerpetualInventoryLogAuditWithRequestBuilder(perpetualInventoryLogId perpetualInventoryLogId: Int, perpetualInventoryLogAudit: String) -> RequestBuilder<Void> {
        var path = "/beta/perpetualInventoryLog/{perpetualInventoryLogId}/audit/{perpetualInventoryLogAudit}"
        path = path.stringByReplacingOccurrencesOfString("{perpetualInventoryLogId}", withString: "\(perpetualInventoryLogId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{perpetualInventoryLogAudit}", withString: "\(perpetualInventoryLogAudit)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     Add new tags for a perpetualInventoryLog.
     
     - parameter perpetualInventoryLogId: (path) Id of the perpetualInventoryLog to add a tag to 
     - parameter perpetualInventoryLogTag: (path) The tag to add 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addPerpetualInventoryLogTag(perpetualInventoryLogId perpetualInventoryLogId: Int, perpetualInventoryLogTag: String, completion: ((error: ErrorType?) -> Void)) {
        addPerpetualInventoryLogTagWithRequestBuilder(perpetualInventoryLogId: perpetualInventoryLogId, perpetualInventoryLogTag: perpetualInventoryLogTag).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     Add new tags for a perpetualInventoryLog.
     
     - PUT /beta/perpetualInventoryLog/{perpetualInventoryLogId}/tag/{perpetualInventoryLogTag}
     - Adds a tag to an existing perpetualInventoryLog.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter perpetualInventoryLogId: (path) Id of the perpetualInventoryLog to add a tag to 
     - parameter perpetualInventoryLogTag: (path) The tag to add 

     - returns: RequestBuilder<Void> 
     */
    public class func addPerpetualInventoryLogTagWithRequestBuilder(perpetualInventoryLogId perpetualInventoryLogId: Int, perpetualInventoryLogTag: String) -> RequestBuilder<Void> {
        var path = "/beta/perpetualInventoryLog/{perpetualInventoryLogId}/tag/{perpetualInventoryLogTag}"
        path = path.stringByReplacingOccurrencesOfString("{perpetualInventoryLogId}", withString: "\(perpetualInventoryLogId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{perpetualInventoryLogTag}", withString: "\(perpetualInventoryLogTag)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     Delete a tag for a perpetualInventoryLog.
     
     - parameter perpetualInventoryLogId: (path) Id of the perpetualInventoryLog to remove tag from 
     - parameter perpetualInventoryLogTag: (path) The tag to delete 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deletePerpetualInventoryLogTag(perpetualInventoryLogId perpetualInventoryLogId: Int, perpetualInventoryLogTag: String, completion: ((error: ErrorType?) -> Void)) {
        deletePerpetualInventoryLogTagWithRequestBuilder(perpetualInventoryLogId: perpetualInventoryLogId, perpetualInventoryLogTag: perpetualInventoryLogTag).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     Delete a tag for a perpetualInventoryLog.
     
     - DELETE /beta/perpetualInventoryLog/{perpetualInventoryLogId}/tag/{perpetualInventoryLogTag}
     - Deletes an existing perpetualInventoryLog tag using the specified data.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter perpetualInventoryLogId: (path) Id of the perpetualInventoryLog to remove tag from 
     - parameter perpetualInventoryLogTag: (path) The tag to delete 

     - returns: RequestBuilder<Void> 
     */
    public class func deletePerpetualInventoryLogTagWithRequestBuilder(perpetualInventoryLogId perpetualInventoryLogId: Int, perpetualInventoryLogTag: String) -> RequestBuilder<Void> {
        var path = "/beta/perpetualInventoryLog/{perpetualInventoryLogId}/tag/{perpetualInventoryLogTag}"
        path = path.stringByReplacingOccurrencesOfString("{perpetualInventoryLogId}", withString: "\(perpetualInventoryLogId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{perpetualInventoryLogTag}", withString: "\(perpetualInventoryLogTag)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     Get a duplicated a perpetualInventoryLog by id
     
     - parameter perpetualInventoryLogId: (path) Id of the perpetualInventoryLog to be duplicated. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getDuplicatePerpetualInventoryLogById(perpetualInventoryLogId perpetualInventoryLogId: Int, completion: ((data: PerpetualInventoryLog?, error: ErrorType?) -> Void)) {
        getDuplicatePerpetualInventoryLogByIdWithRequestBuilder(perpetualInventoryLogId: perpetualInventoryLogId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Get a duplicated a perpetualInventoryLog by id
     
     - GET /beta/perpetualInventoryLog/duplicate/{perpetualInventoryLogId}
     - Returns a duplicated perpetualInventoryLog identified by the specified id.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{contentType=application/json, example={
  "sampleTo" : "aeiou",
  "budgetCode" : "aeiou",
  "interimFact" : 1.3579000000000001069366817318950779736042022705078125,
  "legacyPoNo" : "aeiou",
  "weightPerWrap" : 1.3579000000000001069366817318950779736042022705078125,
  "vendorId" : 123,
  "itemAllocationRule" : "aeiou",
  "oddQuantity" : 123,
  "orderQuantity" : 123,
  "voidDate" : "2000-01-23T04:56:07.000+0000",
  "revDate" : "aeiou",
  "unitsPerCase" : 123,
  "itemStorageLotMixingRule" : "aeiou",
  "lineNo" : 123,
  "unitCode" : "aeiou",
  "id" : 123,
  "sku" : "aeiou",
  "itemForwardItemMixingRule" : "aeiou",
  "currentQuantity" : 123,
  "pricingPer" : "aeiou",
  "receivedDate" : "2000-01-23T04:56:07.000+0000",
  "skuId" : 123,
  "mlCost" : 1.3579000000000001069366817318950779736042022705078125,
  "lobId" : 123,
  "height" : 1.3579000000000001069366817318950779736042022705078125,
  "updatedAt" : "2000-01-23T04:56:07.000+0000",
  "chargeFreight" : "aeiou",
  "itemWarehouseDisplayField" : "aeiou",
  "accountingCode" : "aeiou",
  "taxExempt" : "aeiou",
  "itemForwardLotMixingRule" : "aeiou",
  "artBack" : "aeiou",
  "lastAct" : "2000-01-23T04:56:07.000+0000",
  "itemBarcodeField" : "aeiou",
  "capitalize" : "aeiou",
  "itemReceiptLocationId" : 123,
  "warehouseId" : 123,
  "maxUnders" : 123,
  "interimQuantity" : 123,
  "receivedQuantity" : 123,
  "receiptNo" : 123,
  "requestedDeliveryDate" : "2000-01-23T04:56:07.000+0000",
  "itemStorageItemMixingRule" : "aeiou",
  "asnId" : 123,
  "dockDate" : "2000-01-23T04:56:07.000+0000",
  "asnLine" : 123,
  "itemProductIdTagSchemeId" : 123,
  "orderDate" : "2000-01-23T04:56:07.000+0000",
  "receiptStatus" : "aeiou",
  "factCost" : 1.3579000000000001069366817318950779736042022705078125,
  "endQuantity" : 123,
  "maxFreight" : 1.3579000000000001069366817318950779736042022705078125,
  "norcs" : "aeiou",
  "mlVendor" : 123,
  "customFields" : {
    "key" : "{}"
  },
  "origin" : "aeiou",
  "warehouseLocationId" : 123,
  "endFact" : 1.3579000000000001069366817318950779736042022705078125,
  "enteredBy" : "aeiou",
  "caseWeight" : 1.3579000000000001069366817318950779736042022705078125,
  "locationStatus" : "aeiou",
  "distDate" : "2000-01-23T04:56:07.000+0000",
  "endVal" : 1.3579000000000001069366817318950779736042022705078125,
  "wrapCode" : "aeiou",
  "sfpComplete" : "aeiou",
  "bsVendor" : 123,
  "receivedBy" : "aeiou",
  "unitsPerWrap" : 123,
  "address" : "aeiou",
  "cost" : 1.3579000000000001069366817318950779736042022705078125,
  "interimVal" : 1.3579000000000001069366817318950779736042022705078125,
  "sell" : 1.3579000000000001069366817318950779736042022705078125,
  "length" : 1.3579000000000001069366817318950779736042022705078125,
  "maxOvers" : 123,
  "productIdTag" : "aeiou",
  "impressions" : 123,
  "sample" : 123,
  "fromProd" : 123,
  "paidFull" : "aeiou",
  "prodLot" : "aeiou",
  "width" : 1.3579000000000001069366817318950779736042022705078125,
  "receivedSfp" : 123,
  "accrual" : "aeiou",
  "freightCost" : 1.3579000000000001069366817318950779736042022705078125,
  "itemReceiptId" : 123,
  "maxOther" : 1.3579000000000001069366817318950779736042022705078125,
  "freezeAction" : "aeiou"
}}]
     
     - parameter perpetualInventoryLogId: (path) Id of the perpetualInventoryLog to be duplicated. 

     - returns: RequestBuilder<PerpetualInventoryLog> 
     */
    public class func getDuplicatePerpetualInventoryLogByIdWithRequestBuilder(perpetualInventoryLogId perpetualInventoryLogId: Int) -> RequestBuilder<PerpetualInventoryLog> {
        var path = "/beta/perpetualInventoryLog/duplicate/{perpetualInventoryLogId}"
        path = path.stringByReplacingOccurrencesOfString("{perpetualInventoryLogId}", withString: "\(perpetualInventoryLogId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<PerpetualInventoryLog>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     Search perpetualInventoryLogs by filter
     
     - parameter filter: (query) Query string, used to filter results. (optional)
     - parameter page: (query) Result page number.  Defaults to 1. (optional)
     - parameter limit: (query) Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     - parameter sort: (query) Sort results by specified field. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getPerpetualInventoryLogByFilter(filter filter: String?, page: Int?, limit: Int?, sort: String?, completion: ((data: [PerpetualInventoryLog]?, error: ErrorType?) -> Void)) {
        getPerpetualInventoryLogByFilterWithRequestBuilder(filter: filter, page: page, limit: limit, sort: sort).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Search perpetualInventoryLogs by filter
     
     - GET /beta/perpetualInventoryLog/search
     - Returns the list of perpetualInventoryLogs that match the given filter.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{contentType=application/json, example=[ {
  "sampleTo" : "aeiou",
  "budgetCode" : "aeiou",
  "interimFact" : 1.3579000000000001069366817318950779736042022705078125,
  "legacyPoNo" : "aeiou",
  "weightPerWrap" : 1.3579000000000001069366817318950779736042022705078125,
  "vendorId" : 123,
  "itemAllocationRule" : "aeiou",
  "oddQuantity" : 123,
  "orderQuantity" : 123,
  "voidDate" : "2000-01-23T04:56:07.000+0000",
  "revDate" : "aeiou",
  "unitsPerCase" : 123,
  "itemStorageLotMixingRule" : "aeiou",
  "lineNo" : 123,
  "unitCode" : "aeiou",
  "id" : 123,
  "sku" : "aeiou",
  "itemForwardItemMixingRule" : "aeiou",
  "currentQuantity" : 123,
  "pricingPer" : "aeiou",
  "receivedDate" : "2000-01-23T04:56:07.000+0000",
  "skuId" : 123,
  "mlCost" : 1.3579000000000001069366817318950779736042022705078125,
  "lobId" : 123,
  "height" : 1.3579000000000001069366817318950779736042022705078125,
  "updatedAt" : "2000-01-23T04:56:07.000+0000",
  "chargeFreight" : "aeiou",
  "itemWarehouseDisplayField" : "aeiou",
  "accountingCode" : "aeiou",
  "taxExempt" : "aeiou",
  "itemForwardLotMixingRule" : "aeiou",
  "artBack" : "aeiou",
  "lastAct" : "2000-01-23T04:56:07.000+0000",
  "itemBarcodeField" : "aeiou",
  "capitalize" : "aeiou",
  "itemReceiptLocationId" : 123,
  "warehouseId" : 123,
  "maxUnders" : 123,
  "interimQuantity" : 123,
  "receivedQuantity" : 123,
  "receiptNo" : 123,
  "requestedDeliveryDate" : "2000-01-23T04:56:07.000+0000",
  "itemStorageItemMixingRule" : "aeiou",
  "asnId" : 123,
  "dockDate" : "2000-01-23T04:56:07.000+0000",
  "asnLine" : 123,
  "itemProductIdTagSchemeId" : 123,
  "orderDate" : "2000-01-23T04:56:07.000+0000",
  "receiptStatus" : "aeiou",
  "factCost" : 1.3579000000000001069366817318950779736042022705078125,
  "endQuantity" : 123,
  "maxFreight" : 1.3579000000000001069366817318950779736042022705078125,
  "norcs" : "aeiou",
  "mlVendor" : 123,
  "customFields" : {
    "key" : "{}"
  },
  "origin" : "aeiou",
  "warehouseLocationId" : 123,
  "endFact" : 1.3579000000000001069366817318950779736042022705078125,
  "enteredBy" : "aeiou",
  "caseWeight" : 1.3579000000000001069366817318950779736042022705078125,
  "locationStatus" : "aeiou",
  "distDate" : "2000-01-23T04:56:07.000+0000",
  "endVal" : 1.3579000000000001069366817318950779736042022705078125,
  "wrapCode" : "aeiou",
  "sfpComplete" : "aeiou",
  "bsVendor" : 123,
  "receivedBy" : "aeiou",
  "unitsPerWrap" : 123,
  "address" : "aeiou",
  "cost" : 1.3579000000000001069366817318950779736042022705078125,
  "interimVal" : 1.3579000000000001069366817318950779736042022705078125,
  "sell" : 1.3579000000000001069366817318950779736042022705078125,
  "length" : 1.3579000000000001069366817318950779736042022705078125,
  "maxOvers" : 123,
  "productIdTag" : "aeiou",
  "impressions" : 123,
  "sample" : 123,
  "fromProd" : 123,
  "paidFull" : "aeiou",
  "prodLot" : "aeiou",
  "width" : 1.3579000000000001069366817318950779736042022705078125,
  "receivedSfp" : 123,
  "accrual" : "aeiou",
  "freightCost" : 1.3579000000000001069366817318950779736042022705078125,
  "itemReceiptId" : 123,
  "maxOther" : 1.3579000000000001069366817318950779736042022705078125,
  "freezeAction" : "aeiou"
} ]}]
     
     - parameter filter: (query) Query string, used to filter results. (optional)
     - parameter page: (query) Result page number.  Defaults to 1. (optional)
     - parameter limit: (query) Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     - parameter sort: (query) Sort results by specified field. (optional)

     - returns: RequestBuilder<[PerpetualInventoryLog]> 
     */
    public class func getPerpetualInventoryLogByFilterWithRequestBuilder(filter filter: String?, page: Int?, limit: Int?, sort: String?) -> RequestBuilder<[PerpetualInventoryLog]> {
        let path = "/beta/perpetualInventoryLog/search"
        let URLString = InfoplusAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [
            "filter": filter,
            "page": page,
            "limit": limit,
            "sort": sort
        ]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<[PerpetualInventoryLog]>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: false)
    }

    /**
     
     Get a perpetualInventoryLog by id
     
     - parameter perpetualInventoryLogId: (path) Id of the perpetualInventoryLog to be returned. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getPerpetualInventoryLogById(perpetualInventoryLogId perpetualInventoryLogId: Int, completion: ((data: PerpetualInventoryLog?, error: ErrorType?) -> Void)) {
        getPerpetualInventoryLogByIdWithRequestBuilder(perpetualInventoryLogId: perpetualInventoryLogId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     
     Get a perpetualInventoryLog by id
     
     - GET /beta/perpetualInventoryLog/{perpetualInventoryLogId}
     - Returns the perpetualInventoryLog identified by the specified id.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{contentType=application/json, example={
  "sampleTo" : "aeiou",
  "budgetCode" : "aeiou",
  "interimFact" : 1.3579000000000001069366817318950779736042022705078125,
  "legacyPoNo" : "aeiou",
  "weightPerWrap" : 1.3579000000000001069366817318950779736042022705078125,
  "vendorId" : 123,
  "itemAllocationRule" : "aeiou",
  "oddQuantity" : 123,
  "orderQuantity" : 123,
  "voidDate" : "2000-01-23T04:56:07.000+0000",
  "revDate" : "aeiou",
  "unitsPerCase" : 123,
  "itemStorageLotMixingRule" : "aeiou",
  "lineNo" : 123,
  "unitCode" : "aeiou",
  "id" : 123,
  "sku" : "aeiou",
  "itemForwardItemMixingRule" : "aeiou",
  "currentQuantity" : 123,
  "pricingPer" : "aeiou",
  "receivedDate" : "2000-01-23T04:56:07.000+0000",
  "skuId" : 123,
  "mlCost" : 1.3579000000000001069366817318950779736042022705078125,
  "lobId" : 123,
  "height" : 1.3579000000000001069366817318950779736042022705078125,
  "updatedAt" : "2000-01-23T04:56:07.000+0000",
  "chargeFreight" : "aeiou",
  "itemWarehouseDisplayField" : "aeiou",
  "accountingCode" : "aeiou",
  "taxExempt" : "aeiou",
  "itemForwardLotMixingRule" : "aeiou",
  "artBack" : "aeiou",
  "lastAct" : "2000-01-23T04:56:07.000+0000",
  "itemBarcodeField" : "aeiou",
  "capitalize" : "aeiou",
  "itemReceiptLocationId" : 123,
  "warehouseId" : 123,
  "maxUnders" : 123,
  "interimQuantity" : 123,
  "receivedQuantity" : 123,
  "receiptNo" : 123,
  "requestedDeliveryDate" : "2000-01-23T04:56:07.000+0000",
  "itemStorageItemMixingRule" : "aeiou",
  "asnId" : 123,
  "dockDate" : "2000-01-23T04:56:07.000+0000",
  "asnLine" : 123,
  "itemProductIdTagSchemeId" : 123,
  "orderDate" : "2000-01-23T04:56:07.000+0000",
  "receiptStatus" : "aeiou",
  "factCost" : 1.3579000000000001069366817318950779736042022705078125,
  "endQuantity" : 123,
  "maxFreight" : 1.3579000000000001069366817318950779736042022705078125,
  "norcs" : "aeiou",
  "mlVendor" : 123,
  "customFields" : {
    "key" : "{}"
  },
  "origin" : "aeiou",
  "warehouseLocationId" : 123,
  "endFact" : 1.3579000000000001069366817318950779736042022705078125,
  "enteredBy" : "aeiou",
  "caseWeight" : 1.3579000000000001069366817318950779736042022705078125,
  "locationStatus" : "aeiou",
  "distDate" : "2000-01-23T04:56:07.000+0000",
  "endVal" : 1.3579000000000001069366817318950779736042022705078125,
  "wrapCode" : "aeiou",
  "sfpComplete" : "aeiou",
  "bsVendor" : 123,
  "receivedBy" : "aeiou",
  "unitsPerWrap" : 123,
  "address" : "aeiou",
  "cost" : 1.3579000000000001069366817318950779736042022705078125,
  "interimVal" : 1.3579000000000001069366817318950779736042022705078125,
  "sell" : 1.3579000000000001069366817318950779736042022705078125,
  "length" : 1.3579000000000001069366817318950779736042022705078125,
  "maxOvers" : 123,
  "productIdTag" : "aeiou",
  "impressions" : 123,
  "sample" : 123,
  "fromProd" : 123,
  "paidFull" : "aeiou",
  "prodLot" : "aeiou",
  "width" : 1.3579000000000001069366817318950779736042022705078125,
  "receivedSfp" : 123,
  "accrual" : "aeiou",
  "freightCost" : 1.3579000000000001069366817318950779736042022705078125,
  "itemReceiptId" : 123,
  "maxOther" : 1.3579000000000001069366817318950779736042022705078125,
  "freezeAction" : "aeiou"
}}]
     
     - parameter perpetualInventoryLogId: (path) Id of the perpetualInventoryLog to be returned. 

     - returns: RequestBuilder<PerpetualInventoryLog> 
     */
    public class func getPerpetualInventoryLogByIdWithRequestBuilder(perpetualInventoryLogId perpetualInventoryLogId: Int) -> RequestBuilder<PerpetualInventoryLog> {
        var path = "/beta/perpetualInventoryLog/{perpetualInventoryLogId}"
        path = path.stringByReplacingOccurrencesOfString("{perpetualInventoryLogId}", withString: "\(perpetualInventoryLogId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<PerpetualInventoryLog>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

    /**
     
     Get the tags for a perpetualInventoryLog.
     
     - parameter perpetualInventoryLogId: (path) Id of the perpetualInventoryLog to get tags for 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getPerpetualInventoryLogTags(perpetualInventoryLogId perpetualInventoryLogId: Int, completion: ((error: ErrorType?) -> Void)) {
        getPerpetualInventoryLogTagsWithRequestBuilder(perpetualInventoryLogId: perpetualInventoryLogId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     
     Get the tags for a perpetualInventoryLog.
     
     - GET /beta/perpetualInventoryLog/{perpetualInventoryLogId}/tag
     - Get all existing perpetualInventoryLog tags.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter perpetualInventoryLogId: (path) Id of the perpetualInventoryLog to get tags for 

     - returns: RequestBuilder<Void> 
     */
    public class func getPerpetualInventoryLogTagsWithRequestBuilder(perpetualInventoryLogId perpetualInventoryLogId: Int) -> RequestBuilder<Void> {
        var path = "/beta/perpetualInventoryLog/{perpetualInventoryLogId}/tag"
        path = path.stringByReplacingOccurrencesOfString("{perpetualInventoryLogId}", withString: "\(perpetualInventoryLogId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path
        
        let nillableParameters: [String:AnyObject?] = [:]
        let parameters = APIHelper.rejectNil(nillableParameters)

        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: parameters, isBody: true)
    }

}
