//
// RateCardAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Alamofire



public class RateCardAPI: APIBase {
    /**
     Create a rateCard
     
     - parameter body: (body) RateCard to be inserted. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addRateCard(body body: RateCard, completion: ((data: RateCard?, error: ErrorType?) -> Void)) {
        addRateCardWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Create a rateCard
     - POST /beta/rateCard
     - Inserts a new rateCard using the specified data.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{contentType=application/json, example={
  "modifyDate" : "2000-01-23T04:56:07.000+00:00",
  "customFields" : {
    "key" : "{}"
  },
  "weight" : 5.962133916683182377482808078639209270477294921875,
  "carrierServiceId" : 1,
  "rateType" : "rateType",
  "carrier" : "carrier",
  "zone" : 5,
  "rate" : 2.3021358869347654518833223846741020679473876953125,
  "id" : 0,
  "lineOfBusinessId" : 6,
  "effectiveDate" : "2000-01-23T04:56:07.000+00:00",
  "createDate" : "2000-01-23T04:56:07.000+00:00",
  "expirationDate" : "2000-01-23T04:56:07.000+00:00"
}}]
     
     - parameter body: (body) RateCard to be inserted. 

     - returns: RequestBuilder<RateCard> 
     */
    public class func addRateCardWithRequestBuilder(body body: RateCard) -> RequestBuilder<RateCard> {
        let path = "/beta/rateCard"
        let URLString = InfoplusAPI.basePath + path
        let parameters = body.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<RateCard>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Add new audit for a rateCard
     
     - parameter rateCardId: (path) Id of the rateCard to add an audit to 
     - parameter rateCardAudit: (path) The audit to add 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addRateCardAudit(rateCardId rateCardId: Int32, rateCardAudit: String, completion: ((error: ErrorType?) -> Void)) {
        addRateCardAuditWithRequestBuilder(rateCardId: rateCardId, rateCardAudit: rateCardAudit).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Add new audit for a rateCard
     - PUT /beta/rateCard/{rateCardId}/audit/{rateCardAudit}
     - Adds an audit to an existing rateCard.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter rateCardId: (path) Id of the rateCard to add an audit to 
     - parameter rateCardAudit: (path) The audit to add 

     - returns: RequestBuilder<Void> 
     */
    public class func addRateCardAuditWithRequestBuilder(rateCardId rateCardId: Int32, rateCardAudit: String) -> RequestBuilder<Void> {
        var path = "/beta/rateCard/{rateCardId}/audit/{rateCardAudit}"
        path = path.stringByReplacingOccurrencesOfString("{rateCardId}", withString: "\(rateCardId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{rateCardAudit}", withString: "\(rateCardAudit)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Attach a file to a rateCard
     
     - parameter rateCardId: (path) Id of the rateCard to add a file to 
     - parameter fileName: (path) Name of file 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addRateCardFile(rateCardId rateCardId: Int32, fileName: String, completion: ((error: ErrorType?) -> Void)) {
        addRateCardFileWithRequestBuilder(rateCardId: rateCardId, fileName: fileName).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Attach a file to a rateCard
     - POST /beta/rateCard/{rateCardId}/file/{fileName}
     - Adds a file to an existing rateCard.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter rateCardId: (path) Id of the rateCard to add a file to 
     - parameter fileName: (path) Name of file 

     - returns: RequestBuilder<Void> 
     */
    public class func addRateCardFileWithRequestBuilder(rateCardId rateCardId: Int32, fileName: String) -> RequestBuilder<Void> {
        var path = "/beta/rateCard/{rateCardId}/file/{fileName}"
        path = path.stringByReplacingOccurrencesOfString("{rateCardId}", withString: "\(rateCardId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{fileName}", withString: "\(fileName)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Attach a file to a rateCard by URL.
     
     - parameter body: (body) The url and optionly fileName to be used. 
     - parameter rateCardId: (path) Id of the rateCard to add an file to 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addRateCardFileByURL(body body: RecordFile, rateCardId: Int32, completion: ((error: ErrorType?) -> Void)) {
        addRateCardFileByURLWithRequestBuilder(body: body, rateCardId: rateCardId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Attach a file to a rateCard by URL.
     - POST /beta/rateCard/{rateCardId}/file
     - Adds a file to an existing rateCard by URL.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter body: (body) The url and optionly fileName to be used. 
     - parameter rateCardId: (path) Id of the rateCard to add an file to 

     - returns: RequestBuilder<Void> 
     */
    public class func addRateCardFileByURLWithRequestBuilder(body body: RecordFile, rateCardId: Int32) -> RequestBuilder<Void> {
        var path = "/beta/rateCard/{rateCardId}/file"
        path = path.stringByReplacingOccurrencesOfString("{rateCardId}", withString: "\(rateCardId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path
        let parameters = body.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "POST", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Add new tags for a rateCard.
     
     - parameter rateCardId: (path) Id of the rateCard to add a tag to 
     - parameter rateCardTag: (path) The tag to add 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func addRateCardTag(rateCardId rateCardId: Int32, rateCardTag: String, completion: ((error: ErrorType?) -> Void)) {
        addRateCardTagWithRequestBuilder(rateCardId: rateCardId, rateCardTag: rateCardTag).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Add new tags for a rateCard.
     - PUT /beta/rateCard/{rateCardId}/tag/{rateCardTag}
     - Adds a tag to an existing rateCard.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter rateCardId: (path) Id of the rateCard to add a tag to 
     - parameter rateCardTag: (path) The tag to add 

     - returns: RequestBuilder<Void> 
     */
    public class func addRateCardTagWithRequestBuilder(rateCardId rateCardId: Int32, rateCardTag: String) -> RequestBuilder<Void> {
        var path = "/beta/rateCard/{rateCardId}/tag/{rateCardTag}"
        path = path.stringByReplacingOccurrencesOfString("{rateCardId}", withString: "\(rateCardId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{rateCardTag}", withString: "\(rateCardTag)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Delete a rateCard
     
     - parameter rateCardId: (path) Id of the rateCard to be deleted. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteRateCard(rateCardId rateCardId: Int32, completion: ((error: ErrorType?) -> Void)) {
        deleteRateCardWithRequestBuilder(rateCardId: rateCardId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Delete a rateCard
     - DELETE /beta/rateCard/{rateCardId}
     - Deletes the rateCard identified by the specified id.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter rateCardId: (path) Id of the rateCard to be deleted. 

     - returns: RequestBuilder<Void> 
     */
    public class func deleteRateCardWithRequestBuilder(rateCardId rateCardId: Int32) -> RequestBuilder<Void> {
        var path = "/beta/rateCard/{rateCardId}"
        path = path.stringByReplacingOccurrencesOfString("{rateCardId}", withString: "\(rateCardId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Delete a file for a rateCard.
     
     - parameter rateCardId: (path) Id of the rateCard to remove file from 
     - parameter fileId: (path) Id of the file to delete 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteRateCardFile(rateCardId rateCardId: Int32, fileId: Int32, completion: ((error: ErrorType?) -> Void)) {
        deleteRateCardFileWithRequestBuilder(rateCardId: rateCardId, fileId: fileId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Delete a file for a rateCard.
     - DELETE /beta/rateCard/{rateCardId}/file/{fileId}
     - Deletes an existing rateCard file using the specified data.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter rateCardId: (path) Id of the rateCard to remove file from 
     - parameter fileId: (path) Id of the file to delete 

     - returns: RequestBuilder<Void> 
     */
    public class func deleteRateCardFileWithRequestBuilder(rateCardId rateCardId: Int32, fileId: Int32) -> RequestBuilder<Void> {
        var path = "/beta/rateCard/{rateCardId}/file/{fileId}"
        path = path.stringByReplacingOccurrencesOfString("{rateCardId}", withString: "\(rateCardId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{fileId}", withString: "\(fileId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Delete a tag for a rateCard.
     
     - parameter rateCardId: (path) Id of the rateCard to remove tag from 
     - parameter rateCardTag: (path) The tag to delete 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func deleteRateCardTag(rateCardId rateCardId: Int32, rateCardTag: String, completion: ((error: ErrorType?) -> Void)) {
        deleteRateCardTagWithRequestBuilder(rateCardId: rateCardId, rateCardTag: rateCardTag).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Delete a tag for a rateCard.
     - DELETE /beta/rateCard/{rateCardId}/tag/{rateCardTag}
     - Deletes an existing rateCard tag using the specified data.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter rateCardId: (path) Id of the rateCard to remove tag from 
     - parameter rateCardTag: (path) The tag to delete 

     - returns: RequestBuilder<Void> 
     */
    public class func deleteRateCardTagWithRequestBuilder(rateCardId rateCardId: Int32, rateCardTag: String) -> RequestBuilder<Void> {
        var path = "/beta/rateCard/{rateCardId}/tag/{rateCardTag}"
        path = path.stringByReplacingOccurrencesOfString("{rateCardId}", withString: "\(rateCardId)", options: .LiteralSearch, range: nil)
        path = path.stringByReplacingOccurrencesOfString("{rateCardTag}", withString: "\(rateCardTag)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "DELETE", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get a duplicated a rateCard by id
     
     - parameter rateCardId: (path) Id of the rateCard to be duplicated. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getDuplicateRateCardById(rateCardId rateCardId: Int32, completion: ((data: RateCard?, error: ErrorType?) -> Void)) {
        getDuplicateRateCardByIdWithRequestBuilder(rateCardId: rateCardId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get a duplicated a rateCard by id
     - GET /beta/rateCard/duplicate/{rateCardId}
     - Returns a duplicated rateCard identified by the specified id.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{contentType=application/json, example={
  "modifyDate" : "2000-01-23T04:56:07.000+00:00",
  "customFields" : {
    "key" : "{}"
  },
  "weight" : 5.962133916683182377482808078639209270477294921875,
  "carrierServiceId" : 1,
  "rateType" : "rateType",
  "carrier" : "carrier",
  "zone" : 5,
  "rate" : 2.3021358869347654518833223846741020679473876953125,
  "id" : 0,
  "lineOfBusinessId" : 6,
  "effectiveDate" : "2000-01-23T04:56:07.000+00:00",
  "createDate" : "2000-01-23T04:56:07.000+00:00",
  "expirationDate" : "2000-01-23T04:56:07.000+00:00"
}}]
     
     - parameter rateCardId: (path) Id of the rateCard to be duplicated. 

     - returns: RequestBuilder<RateCard> 
     */
    public class func getDuplicateRateCardByIdWithRequestBuilder(rateCardId rateCardId: Int32) -> RequestBuilder<RateCard> {
        var path = "/beta/rateCard/duplicate/{rateCardId}"
        path = path.stringByReplacingOccurrencesOfString("{rateCardId}", withString: "\(rateCardId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<RateCard>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Search rateCards by filter
     
     - parameter filter: (query) Query string, used to filter results. (optional)
     - parameter page: (query) Result page number.  Defaults to 1. (optional)
     - parameter limit: (query) Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     - parameter sort: (query) Sort results by specified field. (optional)
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getRateCardByFilter(filter filter: String? = nil, page: Int32? = nil, limit: Int32? = nil, sort: String? = nil, completion: ((data: [RateCard]?, error: ErrorType?) -> Void)) {
        getRateCardByFilterWithRequestBuilder(filter: filter, page: page, limit: limit, sort: sort).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Search rateCards by filter
     - GET /beta/rateCard/search
     - Returns the list of rateCards that match the given filter.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{contentType=application/json, example=[ {
  "modifyDate" : "2000-01-23T04:56:07.000+00:00",
  "customFields" : {
    "key" : "{}"
  },
  "weight" : 5.962133916683182377482808078639209270477294921875,
  "carrierServiceId" : 1,
  "rateType" : "rateType",
  "carrier" : "carrier",
  "zone" : 5,
  "rate" : 2.3021358869347654518833223846741020679473876953125,
  "id" : 0,
  "lineOfBusinessId" : 6,
  "effectiveDate" : "2000-01-23T04:56:07.000+00:00",
  "createDate" : "2000-01-23T04:56:07.000+00:00",
  "expirationDate" : "2000-01-23T04:56:07.000+00:00"
}, {
  "modifyDate" : "2000-01-23T04:56:07.000+00:00",
  "customFields" : {
    "key" : "{}"
  },
  "weight" : 5.962133916683182377482808078639209270477294921875,
  "carrierServiceId" : 1,
  "rateType" : "rateType",
  "carrier" : "carrier",
  "zone" : 5,
  "rate" : 2.3021358869347654518833223846741020679473876953125,
  "id" : 0,
  "lineOfBusinessId" : 6,
  "effectiveDate" : "2000-01-23T04:56:07.000+00:00",
  "createDate" : "2000-01-23T04:56:07.000+00:00",
  "expirationDate" : "2000-01-23T04:56:07.000+00:00"
} ]}]
     
     - parameter filter: (query) Query string, used to filter results. (optional)
     - parameter page: (query) Result page number.  Defaults to 1. (optional)
     - parameter limit: (query) Maximum results per page.  Defaults to 20.  Max allowed value is 250. (optional)
     - parameter sort: (query) Sort results by specified field. (optional)

     - returns: RequestBuilder<[RateCard]> 
     */
    public class func getRateCardByFilterWithRequestBuilder(filter filter: String? = nil, page: Int32? = nil, limit: Int32? = nil, sort: String? = nil) -> RequestBuilder<[RateCard]> {
        let path = "/beta/rateCard/search"
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [
            "filter": filter,
            "page": page?.encodeToJSON(),
            "limit": limit?.encodeToJSON(),
            "sort": sort
        ]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<[RateCard]>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: false)
    }

    /**
     Get a rateCard by id
     
     - parameter rateCardId: (path) Id of the rateCard to be returned. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getRateCardById(rateCardId rateCardId: Int32, completion: ((data: RateCard?, error: ErrorType?) -> Void)) {
        getRateCardByIdWithRequestBuilder(rateCardId: rateCardId).execute { (response, error) -> Void in
            completion(data: response?.body, error: error);
        }
    }


    /**
     Get a rateCard by id
     - GET /beta/rateCard/{rateCardId}
     - Returns the rateCard identified by the specified id.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     - examples: [{contentType=application/json, example={
  "modifyDate" : "2000-01-23T04:56:07.000+00:00",
  "customFields" : {
    "key" : "{}"
  },
  "weight" : 5.962133916683182377482808078639209270477294921875,
  "carrierServiceId" : 1,
  "rateType" : "rateType",
  "carrier" : "carrier",
  "zone" : 5,
  "rate" : 2.3021358869347654518833223846741020679473876953125,
  "id" : 0,
  "lineOfBusinessId" : 6,
  "effectiveDate" : "2000-01-23T04:56:07.000+00:00",
  "createDate" : "2000-01-23T04:56:07.000+00:00",
  "expirationDate" : "2000-01-23T04:56:07.000+00:00"
}}]
     
     - parameter rateCardId: (path) Id of the rateCard to be returned. 

     - returns: RequestBuilder<RateCard> 
     */
    public class func getRateCardByIdWithRequestBuilder(rateCardId rateCardId: Int32) -> RequestBuilder<RateCard> {
        var path = "/beta/rateCard/{rateCardId}"
        path = path.stringByReplacingOccurrencesOfString("{rateCardId}", withString: "\(rateCardId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<RateCard>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get the files for a rateCard.
     
     - parameter rateCardId: (path) Id of the rateCard to get files for 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getRateCardFiles(rateCardId rateCardId: Int32, completion: ((error: ErrorType?) -> Void)) {
        getRateCardFilesWithRequestBuilder(rateCardId: rateCardId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Get the files for a rateCard.
     - GET /beta/rateCard/{rateCardId}/file
     - Get all existing rateCard files.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter rateCardId: (path) Id of the rateCard to get files for 

     - returns: RequestBuilder<Void> 
     */
    public class func getRateCardFilesWithRequestBuilder(rateCardId rateCardId: Int32) -> RequestBuilder<Void> {
        var path = "/beta/rateCard/{rateCardId}/file"
        path = path.stringByReplacingOccurrencesOfString("{rateCardId}", withString: "\(rateCardId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Get the tags for a rateCard.
     
     - parameter rateCardId: (path) Id of the rateCard to get tags for 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func getRateCardTags(rateCardId rateCardId: Int32, completion: ((error: ErrorType?) -> Void)) {
        getRateCardTagsWithRequestBuilder(rateCardId: rateCardId).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Get the tags for a rateCard.
     - GET /beta/rateCard/{rateCardId}/tag
     - Get all existing rateCard tags.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter rateCardId: (path) Id of the rateCard to get tags for 

     - returns: RequestBuilder<Void> 
     */
    public class func getRateCardTagsWithRequestBuilder(rateCardId rateCardId: Int32) -> RequestBuilder<Void> {
        var path = "/beta/rateCard/{rateCardId}/tag"
        path = path.stringByReplacingOccurrencesOfString("{rateCardId}", withString: "\(rateCardId)", options: .LiteralSearch, range: nil)
        let URLString = InfoplusAPI.basePath + path

        let nillableParameters: [String:AnyObject?] = [:]
 
        let parameters = APIHelper.rejectNil(nillableParameters)
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

    /**
     Update a rateCard
     
     - parameter body: (body) RateCard to be updated. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    public class func updateRateCard(body body: RateCard, completion: ((error: ErrorType?) -> Void)) {
        updateRateCardWithRequestBuilder(body: body).execute { (response, error) -> Void in
            completion(error: error);
        }
    }


    /**
     Update a rateCard
     - PUT /beta/rateCard
     - Updates an existing rateCard using the specified data.
     - API Key:
       - type: apiKey API-Key 
       - name: api_key
     
     - parameter body: (body) RateCard to be updated. 

     - returns: RequestBuilder<Void> 
     */
    public class func updateRateCardWithRequestBuilder(body body: RateCard) -> RequestBuilder<Void> {
        let path = "/beta/rateCard"
        let URLString = InfoplusAPI.basePath + path
        let parameters = body.encodeToJSON() as? [String:AnyObject]
 
        let convertedParameters = APIHelper.convertBoolToString(parameters)
 
        let requestBuilder: RequestBuilder<Void>.Type = InfoplusAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "PUT", URLString: URLString, parameters: convertedParameters, isBody: true)
    }

}
